bitzesty/qavs-v2

app/views/admin/dashboard/_navigation.html.slim
app/views/admin/form_answers/list_components/_table.html.slim
app/views/admin/form_answers/list_components/_table_body.html.slim
app/views/admin/form_answers/show.html.slim
app/views/admin/users/_debounce_api_check_details.html.slim
app/views/admin/users/_navigation.html.slim
app/views/admin/users/edit.html.slim
app/views/admin/users/new.html.slim
app/views/assessor/form_answers/_category_tabs.html.slim
app/views/assessor/form_answers/_list_body.html.slim
app/views/assessor/form_answers/show.html.slim
app/views/qae_form/_textarea_question.html.slim

- Changed role from 'list' to 'navigation'
- Added table heading to final column in admin index
- Removed link from company name in application index table, for admins and assessors. Also now showing 'Not yet specified' if company name is nil rather than 'Not found', and 'Draft id:' if reference is not yet generated instead of 'Not generated'
- Made left panel on application show page an aside element with aria-label 
- Added empty alt='' tags to images that should be skipped by screen readers
- Removed banners on New User pages

Accessibility updates 2

---

app/views/admin/form_answers/list_components/_table_body.html.slim

Removes the view icon from the nomination row to make more accessible.

removes icon from dashboard

---

app/assets/javascripts/admin/form_answers.js.coffee
app/assets/stylesheets/admin/page-applications.scss
app/controllers/admin/lieutenant_assignment_collections_controller.rb
app/models/lieutenant_assignment_collection.rb
app/views/admin/form_answers/_bulk_assignment.html.slim
app/views/admin/form_answers/index.html.slim
app/views/admin/form_answers/list_components/_table.html.slim
app/views/admin/form_answers/list_components/_table_body.html.slim
spec/features/admin/form_answers/bulk_lieutenants_assignment_spec.rb

https://drive.google.com/file/d/1soVr-PhHbDhAZdTBbjjOLqYNwhgfUYZM/view
Adds column for URN and displays not generated when urn not found.
Adds column for nominee postcode.
Displays an assigned tag below ceremonial county once assigned to lieutenancy.
Displays the checkbox selected total alongside bulk assignment buttons.
Repeats bulk assignment component below table.
Adds flash notice after assigning lieutenancy

admin dashboard UI additions

---

app/controllers/group_leader/dashboard_controller.rb
app/controllers/palace_invites_controller.rb
app/forms/palace_invite_form.rb
app/views/group_leader/dashboard/show.html.slim
app/views/palace_invites/_form.html.slim

Before this commit a palace invite needed to be created before a group leader could log in. This commit changes this by:
- When group leader logs in - if palace invite is not found then created.
- Adds name to submit button to submit instead of update and validations are now run on palace attendees - and changes palace_invited.submitted to true, which is then shown on the group leader dashboard.
- Changes creation of palace attendees to remove javascript and add/remove links. If no attendees are linked to the invite then 2 attendees are created.

finds invite by id instead of token

---

config/routes.rb

This PR removes the devise sign in success notice for all users. The session controller removes the flash notice after the session#create action, this PR applies the route to all user types.

removes sign_in notice for all user types

---

app/assets/stylesheets/frontend/forms.scss
app/javascript/packs/application.js
app/views/group_leader/citations/edit.html.slim
app/views/layouts/application.html.slim
spec/features/group_leaders/citation_spec.rb

- adds dashboard nav link
- adds a confirmation checkbox to the citation page
- once checkbox is selected the question is hidden and the form is displayed
Content to be confirmed and persistence state for acceptance to be added at a later date

group leader UI tweaks

---

app/assets/stylesheets/application-admin.scss
app/views/admin/assessors/_form.html.slim
app/views/admin/assessors/edit.html.slim
app/views/admin/assessors/new.html.slim

https://docs.google.com/spreadsheets/d/1DKkfFLgnpT3MYHUWoZu86tUblJ6h815jh2dMSehQxZA/edit#gid=0
Admin editing/adding assessors
#19 per above spreadsheet
- changes header copy to match designs
- makes label style consistent
- updates password labels as per design
#20 per above spreadsheet
- matches input widths to design
Bulk assign assessors
#26 per above spreadsheet
- widens the notice to display message on one line

admin assessors UI tweaks

---

app/assets/stylesheets/admin/tables.scss
app/assets/stylesheets/application-admin.scss
app/assets/stylesheets/frontend/tables.scss
app/views/admin/admins/_list.html.slim
app/views/admin/assessors/_list.html.slim
app/views/admin/audit_logs/index.html.slim
app/views/admin/dashboard/_applications_report.html.slim
app/views/admin/dashboard/live_data/_applications_in_progress.html.slim
app/views/admin/dashboard/live_data/_submitted_applications.html.slim
app/views/admin/dashboard/live_data/_summary.html.slim
app/views/admin/dashboard/totals_by_day/_registrations.html.slim
app/views/admin/dashboard/totals_by_month/_registrations.html.slim
app/views/admin/dashboard/totals_by_week/_registrations.html.slim
app/views/admin/form_answers/list_components/_table.html.slim
app/views/admin/group_leaders/_list.html.slim
app/views/admin/lieutenants/_list.html.slim
app/views/admin/users/_list.html.slim
app/views/admin/users_feedbacks/show.html.slim
app/views/assessor/form_answers/index.html.slim
app/views/content_only/cookies.html.slim
app/views/lieutenant/form_answers/index.html.slim
app/views/lieutenant/lieutenants/_list.html.slim
db/structure.sql

This PR increases accessibility for all tables across the application.
HTML changes
- tables are wrapped in a div with a region, and aria-label and a tabindex. The tabindex="0" satisfies WCAG SC 2.1.1 Keyboard (A), which allows a keyboard-only user to tab to the container (giving it focus) and scroll it using the keyboard.
CSS changes
- The overflow: auto satisfies WCAG SC 1.4.10 Reflow (AA) by preventing the entire page from having two axes of scrolling (big table, small viewport).
- The outline covers WCAG SC 2.4.7 Focus Visible (AA), but to be safe on WCAG SC 1.4.11 Non-text Contrast (AA), use an outline color with a 3:1 contrast ratio. Using outline ensures it will be visible in Windows High Contrast Mode.

making tables more accessible

---

app/assets/stylesheets/frontend/views/award_form.scss
app/views/content_only/_pdf_link.html.slim
app/views/content_only/_steps_progress_bar.html.slim
app/views/content_only/info_messages/_award_season_closed.html.slim

https://docs.google.com/spreadsheets/d/1DKkfFLgnpT3MYHUWoZu86tUblJ6h815jh2dMSehQxZA/edit#gid=0
spreadsheet #25 
- fixes the layout of the contact details on the useful information page which had been overlapping
- tweaks to the download icon for the blank pdf download
- tweaks to the download icon position
spreadsheet #29
- fixes styling of closed season award winner message

layout bug fixes

---

app/views/qae_form/_form_footer.html.slim

The info page shouldn't be accessible for local assessors (and is not shown in sidebar) so this removes the back button on step A

removes back button for local assessors

---

app/forms/award_years/v2022/qavs/qavs_step4.rb
app/forms/award_years/v2022/qavs/qavs_step5.rb
app/forms/qae_form_builder/assessor_details_question.rb
app/forms/qae_form_builder/step.rb
app/views/qae_form/_assessor_details_question.html.slim
app/views/qae_form/_step.html.slim
app/views/qae_form/_step_submit.html.slim
app/views/qae_form/confirm.html.slim

- adds automatic saving inset text at top of page
- amends question for assessor details
- changes label for question E8.4
- adds in assessor details question at E8.6
- adds submission inset text for regular lieutenants (no change to advanced lieutenants message)
- adds external link to Privacy Guidelines
- changes success header from black to white text on submission success message

local assessment form amendments

---

app/views/qae_form/_supporter_fields_placeholder.html.slim

- second letter of support form (placeholder) showed warning text

removes unnecessary warning text

---

app/assets/javascripts/application.js.coffee
app/views/qae_form/_form_footer.html.slim
app/views/qae_form/_supporter_letter_attachments.html.slim

[UX issue 56]
This is for admins and assessors viewing a nomination, but with no edit access

Introducing a new button that only navigates, bypassing validations and autosave

---

app/assets/javascripts/frontend/form-validation.js.coffee

Issue 158 https://docs.google.com/spreadsheets/d/1gHPAcUI7i3dlo2i57Z_II7tUrZ_wVImA683OqEWuJKQ/edit#gid=0
When the email question was empty both error messages display so this PR adds a condition, as follows:
If the email question is empty then the error 'This field is required' will display.
If the email question is not empty but invalid then the error 'Not a valid email' will display.

checks for empty string on email validation

---

app/views/lieutenant/lieutenants/_list.html.slim
app/views/lieutenant/lieutenants/_user_types.html.slim
spec/features/admin/lieutenants/manage_spec.rb
spec/features/lieutenant/lieutenant_management_spec.rb

This PR renames the lieutenant roles in the user management screens.
Restricted is renamed to regular
Main is renamed to advanced
Issue 170 https://docs.google.com/spreadsheets/d/1gHPAcUI7i3dlo2i57Z_II7tUrZ_wVImA683OqEWuJKQ/edit#gid=0
Also fixes the path for lieutenants editing users (incorrectly using the admin path)

Lieutenants

---

app/search/form_answer_status/lieutenant_filter.rb

This PR removes submitted state from the default options for the lieutenants filter so that nominations will only show in the index once an admin has marked them as eligible.
Also removes a duplicated 'not-eligible' state

removes submitted status from filter

---

app/assets/javascripts/application-admin.js.coffee
app/assets/javascripts/frontend/ga-optout.js.coffee
app/controllers/content_only_controller.rb
app/javascript/packs/application.js
app/views/content_only/cookie_policy.html.slim
app/views/layouts/application-admin.html.slim
app/views/layouts/application-assessor.html.slim
app/views/layouts/application.html.slim
app/views/layouts/govuk_template.html.erb
package.json
yarn.lock

- The cookie banner, settings page and policy pages arent showing for admin & assessor users 
- there is one cookie missing from the cookie policy and that is the _gat cookie. Please add the details of this cookie to the policy. 
Card: https://app.asana.com/0/1200175839265057/1201036488332009/f

Fixing cookies for assessors and admins

---

app/assets/stylesheets/admin/_variables.scss
app/assets/stylesheets/admin/base.scss
app/forms/award_years/v2022/qavs/qavs_step1.rb
app/forms/award_years/v2022/qavs/qavs_step2.rb
app/forms/award_years/v2022/qavs/qavs_step5.rb
app/forms/qae_form_builder/question.rb
app/views/admin/form_answers/_details_and_letters_of_support.html.slim
app/views/group_leader/dashboard/show.html.slim
app/views/lieutenant/dashboard/show.html.slim
app/views/lieutenant/form_answers/_list_body.html.slim
app/views/qae_form/_address_question.html.slim
app/views/qae_form/_assessor_details_question.html.slim
app/views/qae_form/_question.html.slim

this PR addresses the following accessibility issues:
- missing legends on fieldsets
- missing or orphaned labels
- heading sequencing
- removes aria-labelledby reference where missing (label is legend)
- keeps stylings as requested by UX team
- adds more detail to aria labels for links
- uses grey with better contrast for usernames

lieutenant accessibility audit fixes

---

app/views/layouts/application-admin.html.slim
app/views/layouts/application-assessor.html.slim
app/views/layouts/application-judge.html.slim
app/views/layouts/application-lieutenant.html.slim
app/views/layouts/application.html.slim

This PR changes the link for the accessibility statement in footer to a page in the marketing website.
New page URL: https://qavs.dcms.gov.uk/accessibility-statement-system/
no visual changes.
Card: https://app.asana.com/0/1199154381249427/1201337505430969/f

Changing accessibility statement link in footer

---

app/views/admin/users/index.html.slim
app/views/lieutenant/lieutenants/index.html.slim
spec/acceptance/steps/admin_user_management_steps.rb
spec/features/admin/assessors/manage_spec.rb
spec/features/admin/lieutenants/manage_spec.rb
spec/features/lieutenant/lieutenant_management_spec.rb

this PR fixes the add user button in admin and lieutenant user management pages. As there is no form to submit, a link should be used instead of a button tag.

🔧  fixes add user button

---

app/views/admin/form_answers/_applicant_details.html.slim
app/views/admin/form_answers/_nomination_details.html.slim

https://app.asana.com/0/1200061634447616/1201387817745567
The form_answer/show view is always showing Sub Group 1 as this has not yet been implemented to read from the form_answer attribute. This PR corrects this and adds 'Not assigned' when the sub group does not exist.
Also removes an unused partial view as part of ongoing cleanup.

🔧   corrects sub group

---

app/views/admin/group_leaders/edit.html.slim
app/views/form_award_eligibilities/basic_questions/_years_operating.html.slim
app/views/layouts/govuk_template.html.erb
config/initializers/simple_form.rb

https://docs.google.com/spreadsheets/d/1yVVUHchyKLZkxhzB3ZzLU4JR0jxN3Vdw/edit#gid=1086836074
https://app.asana.com/0/1200175839265057/1201148206487248
Following feedback from an accessibility audit, this PR further improves accessibility.
- removes link style from page header to remove hover effect for non-existent link
- adds legend to years_operating eligibility question by adding a custom wrapper in the simple form confi
- adds breadcrumb to edit group leader page

improves accessibility

---

app/javascript/packs/application.scss
app/javascript/styles/selects.scss
app/views/layouts/govuk_template.html.erb

This PR does the following:
- Remove link hover on service name
- Fixes focus style of GDS accessible autocomplete
- Makes table responsive much earlier
Card: https://app.asana.com/0/1200175839265057/1201148206487248
---
Screenshot

Simple UI fixes after audit feedback

---

app/assets/stylesheets/application-admin.scss
app/assets/stylesheets/frontend/forms.scss
app/assets/stylesheets/frontend/layout.scss
app/views/assessor/form_answers/_edit_nomination_links.html.slim
app/views/assessor/form_answers/edit.html.slim
app/views/lieutenant/dashboard/index.html.slim
app/views/lieutenant/form_answers/edit.html.slim
app/views/qae_form/_form_footer.html.slim
app/views/qae_form/_steps_progress_bar.html.slim

https://app.asana.com/0/1200061634447616/1201513040984351/f
https://docs.google.com/spreadsheets/d/1pcgZUhKP8lRCy-b4EBPzeJCrkhRU77jGbMuHX77r2QM/edit#gid=1057492860
ID 2: hides the submission deadline box for assessors
ID 3: adds sidebar button to return assessors to summary page
ID 3: adds button to local assessment footer
ID 4: changes back link colours on the nomination and local assessment form to blue to make more prominent
ID 6: splits the 'View Nomination and Local Assessment form' button into 2 separate buttons
https://app.asana.com/0/1199154381249427/1201513040984363
copy change on lieutenants dashboard for paragraph beginning 'Each assessment'

🐛  assessor testing feedback 

---

app/javascript/packs/application.js
app/views/qae_form/_form_footer.html.slim
app/views/qae_form/_steps_progress_bar.html.slim

This PR autofocuses on national assessment accordion item when assessors click on 2 different buttons when viewing assessment forms.
Card: https://app.asana.com/0/1200061634447616/1201514725436936

Autofocus on national assessment accordion item

---

app/controllers/admin/form_answers_controller.rb
app/models/reports/assessment.rb
app/models/reports/national_assessments_report.rb
app/models/reports/nomination.rb
app/models/reports/qavs_base.rb
app/views/admin/form_answers/_csv_reports_links.html.slim
app/views/admin/form_answers/_submitted_view.html.slim
spec/models/reports/national_assessments_report_spec.rb

https://app.asana.com/0/1200175839265057/1200311197338523
Assumption was made that we only have 4 assessments per nominations max.
Assessment columns are dynamic and should automatically change for each year's assessment form fields.

assessor assignments report

---

app/views/assessor/form_answers/_question.html.slim
app/views/assessor/form_answers/questions/_address_question.html.slim
app/views/assessor/form_answers/questions/_assessor_details_question.html.slim
app/views/assessor/form_answers/questions/_ceremonial_county_question.html.slim
app/views/assessor/form_answers/questions/_checkbox_seria_question.html.slim
app/views/assessor/form_answers/questions/_confirm_question.html.slim
app/views/assessor/form_answers/questions/_dropdown_question.html.slim
app/views/assessor/form_answers/questions/_header_question.html.slim
app/views/assessor/form_answers/questions/_number_question.html.slim
app/views/assessor/form_answers/questions/_options_question.html.slim
app/views/assessor/form_answers/questions/_supporters_question.html.slim
app/views/assessor/form_answers/questions/_text_question.html.slim
app/views/assessor/form_answers/questions/_textarea_question.html.slim
app/views/qae_form/_step.html.slim
app/views/qae_form/_step_submit.html.slim

https://app.asana.com/0/1200175839265057/1201559758877458/f
Everything is basically the same, cleaned up some conditions for disabled fields.
Remove help copy/notice at the beginning of the form
Remove word limit 
Remove help copy about submission at the end of the form

add alternative nomination view for national assessors

---

app/assets/javascripts/frontend/form-validation.js.coffee
app/forms/award_years/v2022/qavs/qavs_step5.rb
app/forms/qae_form_builder/address_question.rb
app/views/qae_form/_address_question.html.slim

https://app.asana.com/0/1200061634447616/1201672148259126
- Removes the required field for the county dropdown in the local assessment form. This amends the required_sub_fields method in the address_builder to reject fields when the attribute ignore_validations is present. The 'not-required' attribute can then be added when the sub_field is missing from the required_sub_fields array. This also adds select fields when checking javascript validations.

Excludes fields from address question validations

---

app/views/assessor/form_answers/index.html.slim
app/views/lieutenant/form_answers/index.html.slim

https://app.asana.com/0/1200175839265057/1201826854672108
Updates copy for Lieutenants and Assessors nominations table.
Assessor table header becomes 'Nominations for your sub-group'.
Lieutenant table header becomes 'Nominations for your Lieutenancy'.

QAVS-V2-P88 Updates copy for nomination table heading

---

app/views/lieutenant/dashboard/index.html.slim

https://app.asana.com/0/1200175839265057/1201387817745579
The links for logo guidance were pointing to the wrong locations so this commit swaps the links.

[QAVS-V2- P5] Swaps logo guidance links

---

app/models/eligibility/basic.rb
spec/features/users/eligibility_form_fulfillment_spec.rb

https://app.asana.com/0/1200061634447616/1201770785534673
This commit fixes a typo on the eligibility question "How long has the group been operating? (it must have been operating for at least 3 years before nomination)"

Updates eligibility question for a typo

---

app/models/eligibility/basic.rb
app/views/lieutenant/dashboard/index.html.slim
spec/features/users/eligibility_form_fulfillment_spec.rb

Cherry picks https://github.com/bitzesty/qavs-v2/pull/398 and https://github.com/bitzesty/qavs-v2/pull/399 into staging.
Fixes typo on the eligibility question and swaps lord lieutenant logo guidance links

#398 and #399 > staging

---

app/helpers/eligibility_helper.rb
app/models/eligibility/basic.rb
spec/features/users/eligibility_form_fulfillment_spec.rb

https://app.asana.com/0/1199154381249427/1201929204570014
For the question 'Are the majority of the group volunteers?', under No, please can we remove 'permitted in exceptional circumstances'.
https://app.asana.com/0/1199154381249427/1201929204570016
Instead of saying 'how long has the group been operating' we should ask 'how many years has the group been in operation' so they know they just have to enter a number.

[QAVS0222] - Eligibility questions copy changes

---

app/controllers/assessor/form_answers_controller.rb
app/controllers/concerns/form_answer_mixin.rb
app/models/assessor.rb
app/models/award_year.rb
app/models/form_answer.rb
app/views/admin/form_answers/index.html.slim
app/views/assessor/form_answers/index.html.slim
app/views/layouts/_vertical_admin_award_year.html.slim
app/views/lieutenant/form_answers/index.html.slim

https://app.asana.com/0/home/1200061634431011/1202057858108917
- Passes the year as a params in the search to allow year changes to persist when making filter and search queries.
- Permits :search_id and :year as params to allow queries and filters to persist when changing the year.
- Adds the award year select button above the search bar - this differs to the Asana card as quicker to implement.
- Changes the first year to 2022 to match the data imported from the old QAVS. This will stop users being able to select years prior to 2022 (in case they expect to see old data)
- Comments the option to select All Years. Currently due to having different county lists across years this option will behave unpredictably. Can be reinstated when there is a single county list again.
Amends the scope to …

[QAVS0422] Reinstates the award year dropdown on the Nominations dashboard

---

app/controllers/admin/form_answers_controller.rb
app/search/form_answer_search.rb
app/search/form_answer_status/filtering_helper.rb
app/views/admin/form_answers/_csv_reports_links.html.slim
app/views/assessor/form_answers/index.html.slim

Card: https://app.asana.com/0/1199154381249427/1202057858108917/f
- Applies params[:year] to CSV scope.
- Temporarily commenting out filters for assessors
- Allow filtering where activity type is 'not_stated'
- Filter by AwardYear from params[:year] if present

Year filter fixes 

---

app/views/admin/form_answers/list_components/_table_body.html.slim
app/views/admin/form_answers/show.html.slim
app/views/assessor/form_answers/_list_body.html.slim
app/views/assessor/form_answers/show.html.slim
app/views/lieutenant/form_answers/_list_body.html.slim
app/views/lieutenant/form_answers/show.html.slim

https://app.asana.com/0/1200061634447616/1202087269805838
Stop the award year filter from resetting when a user clicks on a nomination and then uses the ‘Back to nominations list’
- passes params for search_id and year when viewing a nomination
- permits params when navigating back to the nomination list
- refactor aria_label when company name is not present

Adds search and year params

---

app/controllers/group_leader/dashboard_controller.rb
app/views/group_leader/dashboard/index.html.slim
spec/features/group_leaders/sign_in_spec.rb

https://app.asana.com/0/1199154381249427/1202103937470460/
Currently, the dates in the group leader dashboard are being pulled from the year that is active. So a group leader from a winning nomination for the year 2022 will see settings from the year 2023 (the year that's currently open).
This needs to be changed so that GL see dates and information for their relevant year.
- updated deadlines in the controller to use settings for the `form_answer.award_year`
- removed hardcoded years in the dashboard

[QAVS0422] - Change GL dashboard settings to reflect nomination year

---

app/models/form_answer.rb
app/services/notifiers/email_notification_service.rb

should only get sent to:
Local assessment - recommended (but not later changed to 'awarded')
Local assessment - not recommended
National assessment - not recommended
https://app.asana.com/0/1199154381249427/1202305344458491

change scope of the unsuccessful GL notifications

---

app/models/form_answer.rb
app/services/notifiers/email_notification_service.rb
app/views/account_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
app/views/account_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim

https://app.asana.com/0/1200061634447616/1202339703930603
Removes personalisation on unsuccessful mailer
Adds new scope for unsuccessful_applications_for_nominator_mailer

[QAVS0522] Changes to the 'UNSUCCESSFUL: Email to nominators

---

app/models/form_answer.rb

https://app.asana.com/0/1199154381249427/1203264867377040
`assign_searching_attributes` is called when saving the form answer.

Remove condition for editing group name

---

app/views/assessor/form_answers/index.html.slim

https://app.asana.com/0/1199154381249427/1203264867377035/f
Adds pagination above the form answer table on the Assessor view

Duplicates pagination above the assessors form_answer table

---

app/controllers/assessor/form_answers_controller.rb
app/models/reports/assessment.rb
app/models/reports/assessor_decisions_report.rb
app/models/reports/nomination.rb
app/views/assessor/form_answers/_csv_reports_links.html.slim
app/views/assessor/form_answers/index.html.slim
spec/models/reports/assessor_decisions_report_spec.rb

https://app.asana.com/0/1199154381249427/1202531355487421
A link is added to the Assessor nominations dashboard for a CSV report displaying an assessor decisions for each form_answer.
The assessors report on the admin dashboard loops through each assessor_assignment by index but here we only want to display the feedback for the current_assessor. 
Where the assessor has not yet provided feedback for that nomination  the column will be empty.

Adds CSV download link for assessors

---

app/models/reports/assessment.rb
app/models/reports/assessor_decisions_report.rb

https://app.asana.com/0/1199154381249427/1202531355487421/f
Additional subtasks:
Removed the filter for submitted assessments when building the assessment for the report.
Added additional column that checks the existence of the submitted_at attribute on the assessment

Shows unsubmitted assessment comments in report

---

app/views/form/support_letters/_support_letter.html.slim
app/views/qae_form/_supporter_fields.html.slim
app/views/qae_form/_supporter_fields_placeholder.html.slim

* supporter_fields - this view displays saved support letters. The Remove button was not destroying the records from the database, only the document so adding in the url and also passing this url as a data attribute along with the remove-supporter class which applies method: delete
* support_letter - fixed aria label
* supporter_fields_placeholder - remove button deleted as ID not present when removing newly added support letter
* https://app.asana.com/0/1199154381249427/1205441207852642
* None

Fix deletion of support letter attachments

---

app/policies/support_letter_policy.rb
app/views/qae_form/_supporter_fields.html.slim

* Adds `can_remove?` policy for letters of support
* https://app.asana.com/0/1199154381249427/1203411987771110/f
* None

Add support letter policy for removal

---

app/views/qae_form/_supporter_fields.html.slim

* Fixing a typo causing letters of support to show twice
* https://app.asana.com/0/1199154381249427/1205441207852642/f
* None

Fix typo causing duplicate support letters

---

app/controllers/admin/lieutenants_controller.rb
app/controllers/admin/users_controller.rb
app/helpers/search_helper.rb
app/models/concerns/soft_delete.rb
app/policies/lieutenant_policy.rb
app/views/admin/lieutenants/_list.html.slim
app/views/admin/users/index.html.slim
app/views/shared/users/_search_count.html.slim
config/routes.rb
spec/features/admin/lieutenants/manage_spec.rb

* add ability to restore lieutenants for admins
* https://app.asana.com/0/1199154381249427/1206111043854989/f
*

add ability to restore lieutenants for admins

---

app/assets/javascripts/frontend/custom_questions/support_letters.js.coffee
app/controllers/users/support_letters_controller.rb
app/views/qae_form/_supporter_fields.html.slim
app/views/qae_form/_supporter_fields_placeholder.html.slim

* fix a bug where right after uploading the button did not appear
* https://app.asana.com/0/1199154381249427/1206476383518318/f
*

add ability to remove letter of support right after upload

---

app/views/qae_form/_supporter_fields.html.slim
app/views/qae_form/_supporters_question.html.slim

* previously we showed the buttons allowing user in theory to bypass the validations and add 3rd letter of support 
* https://app.asana.com/0/1199154381249427/1206476387974016
*

hide buttons after submission deadline is passed if form is not editable

---

app/controllers/form/support_letters_controller.rb
app/views/qae_form/_supporter_fields.html.slim

* add check for button rendering and controller action
* https://app.asana.com/0/1199154381249427/1206476387974026
*

remove ability for assessors/lieutenants to delete support letters

---

.github/workflows/slack_notification.yml

* 
asana: https://app.asana.com/0/1201340677821043/1206487672838476/f
*

Add slack notification only for tests

---

app/views/shared/users/_form_password_settings.html.slim
app/views/shared/users/_password_change.html.slim
app/views/shared/users/_password_guidance.html.slim
config/initializers/devise.rb
spec/models/admin_spec.rb

* Updates devise config to use 14 minimum characters
* Updates js file to show error when input is less than 14 characters
* Updates help copy with new value
* https://app.asana.com/0/1199154381249427/1206408878957792/f
* None

Increases password minimum length to 14 characters

---

app/views/admins/registrations/new.html.slim
app/views/shared/users/_form_password_settings.html.slim
app/views/users/registrations/new.html.slim

* Adds min password to views to fix help copy
* https://github.com/bitzesty/qavs-v2/pull/653
* https://app.asana.com/0/1199154381249427/1206408878957792/f
* None

Adds min password to views

---

app/controllers/assessor/form_answers_controller.rb
app/services/assessor_assignment_service.rb
app/views/assessor/form_answers/_list_body.html.slim
app/views/assessor/form_answers/index.html.slim
db/migrate/20240216144428_add_status_to_assessor_assignments.rb
db/structure.sql

* Removes status column and sub group column from assessors form answer table
* Adds a new column to display status of assessment - column shows status tabs for 'Viewed', 'In progress' and 'Submitted'
* Adds a status column to the AssessorAssignments table in the database.
* 'Viewed' will display after the assessor has viewed the application using the buttons on the summary page. These use the edit method in form_answers controller so if status is not yet set, the status will be updated to 'viewed'. AssessorAssignments may not be created at this stage so we check and create if it doesn't exist.
* 'In progress' will display after the assessor has edited the assessment form. This is the 'save' action in the AssessorAssignment controller and changes the status to 'in_progress'. There are no …

Adds statuses to assessor assignments

---

Dockerfile

Remove npm from Dockerfile because conflict versions - nodejs already has npm
* 
*

Remove npm from Dockerfile because conflict versions - nodejs already has npm

---

app/views/form/support_letters/_form.html.slim
app/views/form/supporters/index.html.slim

Related to #697 
- build `SuportLetter` association if none exist
Asana card here: https://app.asana.com/0/1199154381249427/1206750664011265/f
None

Build support letters if none are present in non-JS version

---

app/assets/javascripts/application.js.coffee
config/initializers/ckeditor.rb

Signed-off-by: Louis Kirkham <louis.kirkham@bitzesty.com>
* This PR disables the warning for the CK editor warning. It is a temporary fix to hide the warning from users while we apply a major upgrade to CKeditor.
* https://app.asana.com/0/1199154381249427/1207754952747949/f
* None

Disables ckeditor version warning

---

app/search/nomination_stats_search.rb
app/views/admin/statistics/nomination_mailer/notify.text.erb
app/views/admin/statistics/nominations/index.html.slim

Some minor fixes to the new statistic table feature
* Default search was not returning the Not Assigned row so we have reverted back to the shared AdminFilter that is used for other Lieutenancy filters.
* Uses 'Not Assigned' for the unassigned row
* Copy change on the email
* https://app.asana.com/0/1199154381249427/1208124592841642/f
* None

Fix: Statistics table QA amendments

---

app/assets/javascripts/frontend/custom_questions/support_letters.js.coffee
app/assets/stylesheets/frontend/views/award_form.scss
app/views/form/support_letters/_form.html.slim
app/views/layouts/govuk_template.html.erb
app/views/qae_form/_supporter_fields.html.slim
app/views/support_letters/_attachment.html.slim

- Show status of attachment when first uploaded.
- Correct file name styling to govuk-body.
- Update first name label on support letters form.
* https://app.asana.com/0/1199154381249427/1208164465455881/f
*

Letters of support - form UI tweaks

---

app/helpers/form_answer_helper.rb
app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb
app/pdf_generators/qae_pdf_forms/general/question_pointer.rb
app/views/form/support_letters/_form.html.slim
app/views/qae_form/_supporter_fields.html.slim
forms/award_years/v2025/qavs/qavs_step3.rb

* Letters of support questions are structured as 1 question with 2 entities. The support letters are stored within a supporter_letters_list array:
```
document:
{
"supporter_letters_list"=>
[
{"support_letter_id"=>"",
"first_name"=>"",
"last_name"=>"",
"relationship_to_nominee"=>"",
"letter_of_support"=>""},
{"support_letter_id"=>"",
"first_name"=>"",
"last_name"=>"",
"relationship_to_nominee"=>"",
"letter_of_support"=>""}
]...
```
* Because the PDF generator will interpret this as one question, I am 'mocking' the question refs (C 1.1) so that the PDF version of the question looks like this:
**C1. The first letter of support**
**C1.1. Name of the person who wrote the first letter of support**
First name:
Surname:
**C1.2. Relationship to group**
_For example, a beneficiary of the group, …

Update how form answer PDFs are rendered for supporters question

---

app/assets/stylesheets/application-admin.scss
app/controllers/concerns/form_answer_mixin.rb
app/views/admin/form_answers/_bulk_assignment_button_top.html.slim
app/views/admin/form_answers/bulk_assign_assessors.html.slim
app/views/admin/form_answers/index.html.slim
spec/controllers/admin/form_answers_controller_spec.rb

* Adds anchor to redirect to error message on validation failure
* Hides award year dropdown when javascript disabled.
* Updates `save_or_load_search!` method to include year params. When using the award year dropdown, the search_id is passed in the params but is not updated with the new year param. A check is therefore done to update the search record if the params[:year] does not match.
* When javascript is disabled, a new search record is created. Therefore the search param is removed from the redirect here as we instead use the year from the search record.
* Increases width of the success banner.
* Adds new copy for bulk assign assessors.
* https://app.asana.com/0/1199154381249427/1208415726190878/f
* None

Fix: fixes for bulk assign buttons

---

app/views/group_leader/citations/edit.html.slim

* Copy change to citation page to use the application award year instead of the current award year.
* None

chore: Update variable for award year in group leader citations edit page

---

app/views/group_leader/dashboard/index.html.slim

* Adds variables to media pack links to update automatically each year. Prior to 2023 the link were saved as QAVS so a conditional is added to find the correct filepath.
* Copy change to date range on group leader dashboard
* None

chore: Updates media pack links on group leader dashboard
