- spec/features/admin/form_answers/previous_winnings_spec.rb
- spec/features/admin/reports/assessors_progress_report_csv_spec.rb
- spec/features/assessor/appraisal_form_submission_spec.rb
- spec/features/assessor/bulk_assessors_assignment_spec.rb
- spec/features/assessor/download_original_pdf_before_deadline_ends_spec.rb
- spec/features/assessor/feedback_spec.rb
- spec/features/assessor/list_sorting_spec.rb
- spec/features/assessor/press_summary_spec.rb
- spec/features/assessor/review_audit_certificate_spec.rb
- spec/features/assessor/sorting_by_assessors_spec.rb
- spec/features/assessor/status_filtering_spec.rb
- spec/features/non_js_form_dynamic_lists/current_queens_awards_spec.rb
- spec/features/non_js_form_dynamic_lists/subsidiaries_spec.rb
- spec/form_pointers/form_financial_pointer_spec.rb
- spec/mailers/account_mailers/notify_non_shortlisted_mailer_spec.rb
- spec/mailers/account_mailers/notify_shortlisted_mailer_spec.rb
Sorry Vasili for another PR, just added the comments into the specs.
> Add comments to specs after cleanup

- app/models/reports/admin_report.rb
- app/models/reports/data_pickers/assessor_progress_picker.rb
- app/models/reports/discrepancies_between_primary_and_secondary_appraisals.rb
- app/views/admin/dashboard/downloads/_csv_reports.html.slim
https://app.asana.com/0/1200175839265057/1200311224473841
> [admin dashboard] clean up award categories

- app/controllers/admin/users_controller.rb
- app/controllers/lieutenant/lieutenants_controller.rb
- app/policies/application_policy.rb
- app/policies/lieutenant_policy.rb
- app/views/layouts/application-lieutenant.html.slim
- app/views/lieutenant/lieutenants/_form.html.slim
- app/views/lieutenant/lieutenants/_list.html.slim
- app/views/lieutenant/lieutenants/create.html.slim
- app/views/lieutenant/lieutenants/edit.html.slim
- app/views/lieutenant/lieutenants/index.html.slim
- app/views/lieutenant/lieutenants/new.html.slim
- config/routes.rb
- db/structure.sql
- spec/features/lieutenant/lieutenant_management_spec.rb
- spec/support/user_step_definitions.rb
https://app.asana.com/0/1200175839265057/1200311149768437
> add ability to advanced lieutenant to manage other lieutenants

- app/mailers/application_mailer.rb
- app/views/admins/mailer/confirmation_instructions.text.erb
- app/views/layouts/application.html.slim
- app/views/users/mailer/confirmation_instructions.html.erb
- config/locales/en.yml
- spec/mailers/users/custom_mailer_spec.rb
- spec/mailers/users/submission_spec.rb
https://app.asana.com/0/1200175839265057/1200311141514844
> change user sign in flow copy

- app/assets/javascripts/application.js.coffee
- app/controllers/users/support_letter_attachments_controller.rb
- app/views/qae_form/_supporter_fields.html.slim
https://app.asana.com/0/1200175839265057/1200311082286587
> fix js error and letters of support upload

- app/policies/form_answer_policy.rb
- spec/features/admin/form_answers/view_edit_applications_spec.rb
https://app.asana.com/0/1200175839265057/1200311083152729
> tweak permissions to edit application for admins

- app/forms/award_years/v2022/qavs/qavs_step1.rb
- app/forms/award_years/v2022/qavs/qavs_step4.rb
Adds additional references to the question - both to make the form more accessible and to improve the downloadable PDF version. Also removes the introduction as eligibility forms part of the nomination process.
https://app.asana.com/0/1200175839265057/1200311223733949
> Adds question refs and address headings

- app/controllers/admin/users_controller.rb
- app/controllers/form_controller.rb
- app/models/eligibility.rb
- app/models/eligibility/basic.rb
- app/models/form_answer.rb
- app/policies/user_policy.rb
- app/views/admin/users/_fields_user_details.html.slim
- app/views/admin/users/_form.html.slim
- app/views/content_only/_award_nickname.html.slim
- config/routes.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/features/admin/form_answers/create_spec.rb
- spec/models/eligibility/basic_spec.rb
https://app.asana.com/0/1200175839265057/1200311083204233
> Admin nomination as a user

- app/views/content_only/_guidance_notes.html.slim
- app/views/content_only/award_info_qavs.html.slim
- app/views/content_only/pre_submission_guidance.html.slim
- config/routes.rb
Adds guidance notes to the form.
Links to notes from the dashboard (without PDF download link)
https://app.asana.com/0/1200175839265057/1200311082191702
> Guidance notes for QAVS form

- app/assets/stylesheets/frontend/views/useful-information.scss
- app/views/accounts/useful_information.html.slim
- app/views/admin/audit_logs/index.html.slim
- app/views/admin/dashboard/downloads/_assessors_progress.html.slim
- app/views/admin/dashboard/downloads/_case_summary_link.html.slim
- app/views/admin/dashboard/downloads/_csv_reports.html.slim
- app/views/admin/dashboard/downloads/_pdf_reports.html.slim
- app/views/admin/dashboard/downloads/_primary_vs_secondary_appraisals.html.slim
- app/views/admin/settings/show.html.slim
- app/views/admin/users/index.html.slim
- app/views/admin/users_feedbacks/show.html.slim
- app/views/content_only/privacy.html.slim
- app/views/layouts/application-admin.html.slim
- app/views/layouts/application-assessor.html.slim
- app/views/layouts/application-judge.html.slim
- app/views/layouts/application-lieutenant.html.slim
- app/views/layouts/govuk_template.html.erb
- app/views/layouts/twofactor.html.slim
- Added html language attribute and role='main' to admin, assessor, lieutenant and judge main content
- h1 to admin pages 'Users', Settings', 'Feedback', 'Data Export Log', 'Useful Information' and 'Privacy'
- Added aria-labels to download links
> Accessibility updates

- app/forms/award_years/v2022/qavs/qavs_step1.rb
- app/models/form_answer.rb
- app/search/form_answer_search.rb
- app/search/form_answer_status/admin_filter.rb
- app/search/form_answer_status/filtering_helper.rb
- app/views/admin/form_answers/index.html.slim
- app/views/shared/form_answers/_top_statuses_filters.html.slim
- db/migrate/20210629130552_add_nominee_activity_to_form_answers.rb
- db/structure.sql
- spec/features/admin/form_answers/filtering_by_status_spec.rb
- spec/features/admin/form_answers/list_sorting_spec.rb
- spec/fixtures/form_answer_qavs.json
- spec/support/form_answer_filtering_test_helper.rb
- spec/value_objects/form_paginator_spec.rb
https://app.asana.com/0/1200175839265057/1200311144506352
Adds a dropdown question for group activity.
(Incomplete - Awaiting complete list of options)
Adds a filter option to admin dashboard to search by activity.
(Incomplete - Needs UX)
> Adds activity tag to form

- app/views/accounts/useful_information.html.slim
- app/views/content_only/_steps_progress_bar.html.slim
- app/views/feedbacks/show.html.slim
- app/views/form_award_eligibilities/_steps_progress_bar.html.slim
- app/views/layouts/application.html.slim
- app/views/qae_form/_steps_progress_bar.html.slim
- public/404.html
- public/422.html
Updates the phone number and email to QAVS contact
https://app.asana.com/0/1200175839265057/1200311190767030
> Contact details update

- app/controllers/form_award_eligibilities_controller.rb
- app/models/form_answer.rb
- app/models/form_answer/award_eligibility_builder.rb
- app/views/form_award_eligibilities/_previous_answers.html.slim
- app/views/form_award_eligibilities/show.html.slim
- db/structure.sql
- spec/features/users/eligibility_form_fulfillment_spec.rb
https://app.asana.com/0/1200175839265057/1200311224112406
> fix eiligibility

- app/forms/award_years/v2022/qavs.rb
- app/forms/award_years/v2022/qavs/qavs_step5.rb
- app/forms/qae_form_builder/qae_form.rb
- app/forms/qae_form_builder/qae_form_decorator.rb
- app/forms/qae_form_builder/text_question.rb
- app/helpers/form_helper.rb
- app/validators/form_answer_validator.rb
- app/views/lieutenant/form_answers/_lieutenants_section.html.slim
- spec/features/lieutenant/form_answer_spec.rb
https://app.asana.com/0/1200175839265057/1200311085430209
Adds questions for local assessment form
Todo: PDF download & ethnicity question
> Local assessment form

- app/forms/award_years/v2022/qavs/qavs_step1.rb
- app/search/form_answer_status/admin_filter.rb
- spec/features/admin/form_answers/filtering_by_status_spec.rb
- spec/features/admin/form_answers/list_sorting_spec.rb
- spec/fixtures/form_answer_qavs.json
- spec/value_objects/form_paginator_spec.rb
https://app.asana.com/0/1200175839265057/1200311144506352
Adds QAVS activity type options
> adds additional activity type options

- app/mailers/account_mailers/base_mailer.rb
- app/mailers/lieutenant_mailers/local_assessment_reminder_mailer.rb
- app/models/deadline.rb
- app/models/email_notification.rb
- app/models/settings.rb
- app/renderers/mail_renderer.rb
- app/services/notifiers/email_notification_service.rb
- app/views/admin/settings/deadlines/_shortlisted_stage_deadlines.html.slim
- app/views/admin/settings/deadlines/_shortlisted_stage_email_notifications.html.slim
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/preview/notify.html.slim
- config/locales/en.yml
- spec/mailers/account_mailers/business_apps_winners_mailer_spec.rb
- spec/mailers/account_mailers/notify_non_shortlisted_mailer_spec.rb
- spec/mailers/account_mailers/notify_shortlisted_mailer_spec.rb
- spec/mailers/account_mailers/reminder_to_submit_mailer_spec.rb
- spec/models/settings_spec.rb
- spec/services/notifiers/email_notification_service_spec.rb
https://app.asana.com/0/1200175839265057/1200311149424011
> add new lieutenancy deadlines for shortlisted stage

- app/views/accounts/useful_information.html.slim
- app/views/content_only/_award_nickname.html.slim
- app/views/content_only/_dashboard_pre_submission.html.slim
- app/views/content_only/apply_qavs_award.html.slim
- app/views/content_only/award_info_qavs.html.slim
- app/views/content_only/info_messages/_award_season_closed.html.slim
- app/views/content_only/info_messages/_award_season_opens_soon.html.slim
- app/views/content_only/info_messages/_new_users_message.html.slim
https://docs.google.com/document/d/1XvEyNUzmsrU5mhvRZAPNPqzjfmRU5vbGYBQnTESSTDA/edit?usp=sharing
Adds additional message for new users regarding award deadline status
Removes QAVS information from dashboard and removes QAE message information from top.
Updates header and copy changes to process
Removes guidance notes from Useful Nomination Info section on form
Useful information - updates contacts section and copy changes for completion guidance
> Copy changes

- app/forms/award_years/v2022/qavs/qavs_step2.rb
- app/forms/award_years/v2022/qavs/qavs_step3.rb
- app/forms/award_years/v2022/qavs/qavs_step5.rb
- app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb
Removes conditional for Supporter model.
Removes newlines on long paragraphs.
Adds pdf context for bullet points.
> copy changes for form

- app/controllers/admin/admins_controller.rb
- app/controllers/admin/assessors_controller.rb
- app/controllers/admin/lieutenants_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/lieutenant/lieutenants_controller.rb
- app/models/admin.rb
- app/models/assessor.rb
- app/models/concerns/password_generatable.rb
- app/models/lieutenant.rb
- app/models/user.rb
- app/views/admin/admins/_form.html.slim
- app/views/admin/assessors/_form.html.slim
- app/views/admin/lieutenants/_form.html.slim
- app/views/admin/users/_fields_user_details.html.slim
- app/views/lieutenant/lieutenants/_form.html.slim
- spec/acceptance/steps/admin_user_management_steps.rb
- spec/features/admin/lieutenants/manage_spec.rb
- spec/features/lieutenant/lieutenant_management_spec.rb
https://app.asana.com/0/1200175839265057/1200311145489899
> remove password fields on create

- app/views/admin/settings/deadlines/_local_assessment_email_notifications.html.slim
- app/views/admin/settings/deadlines/_local_assessment_stage_deadlines.html.slim
- app/views/admin/settings/deadlines/_shortlisted_stage_deadlines.html.slim
- app/views/admin/settings/show.html.slim
- app/views/admin/settings/stages/_local_assessment_stage.html.slim
- app/views/admin/settings/stages/_shortlisted_stage.html.slim
https://app.asana.com/0/1200175839265057/1200311149424011
> Move local assessment deadlines to its own section

- app/helpers/eligibility_helper.rb
- app/models/eligibility/basic.rb
- app/models/eligibility/validation/more_than_two_validation.rb
- app/models/eligibility/validation/not_no_validation.rb
- app/views/form_award_eligibilities/_answers.html.slim
- app/views/form_award_eligibilities/basic_questions/_are_majority_volunteers.html.slim
- app/views/form_award_eligibilities/basic_questions/_benefits_animals_only.html.slim
- app/views/form_award_eligibilities/basic_questions/_do_you_file_company_tax_returns.html.slim
- app/views/form_award_eligibilities/basic_questions/_has_at_least_three_people.html.slim
- app/views/form_award_eligibilities/basic_questions/_has_management_and_two_employees.html.slim
- app/views/form_award_eligibilities/basic_questions/_industry.html.slim
- app/views/form_award_eligibilities/basic_questions/_national_organisation.html.slim
- app/views/form_award_eligibilities/basic_questions/_organization_kind.html.slim
- app/views/form_award_eligibilities/basic_questions/_self_contained_enterprise.html.slim
- app/views/form_award_eligibilities/basic_questions/_years_operating.html.slim
- config/locales/en.yml
- db/structure.sql
- spec/factories/eligibility.rb
- spec/features/users/eligibility_form_fulfillment_spec.rb
- spec/models/eligibility/basic_spec.rb
https://app.asana.com/0/1200175839265057/1200311141830733
Updates the QAVS eligibility questions.
Keeps previous_winner question.
> updates eligibility questions

- app/controllers/form_controller.rb
- app/controllers/lieutenant/form_answers_controller.rb
- app/policies/application_policy.rb
- app/policies/form_answer_policy.rb
- app/views/lieutenant/form_answers/edit.html.slim
- app/views/qae_form/_form_footer.html.slim
https://app.asana.com/0/1200175839265057/1200596866366322
https://app.asana.com/0/1200175839265057/1200560530477251
> add basic submission & submission permissions for lieutenants

- app/mailers/lieutenant_mailers/local_assessment_notification_mailer.rb
- app/models/email_notification.rb
- app/renderers/mail_renderer.rb
- app/services/notifiers/email_notification_service.rb
- app/views/admin/settings/deadlines/_local_assessment_email_notifications.html.slim
- app/views/lieutenants_mailers/local_assessment_notification_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_notification_mailer/preview/notify.html.slim
- config/locales/en.yml
- spec/services/notifiers/email_notification_service_spec.rb
https://app.asana.com/0/1200175839265057/1200311084939089
> add local assessment notification mailer

- app/controllers/concerns/form_answers_pdf.rb
- app/controllers/lieutenant/form_answers_controller.rb
- app/controllers/users/form_answers_controller.rb
- app/decorators/form_answer_decorator.rb
- app/models/deadline.rb
- app/models/form_answer.rb
- app/pdf_generators/form_pdf.rb
- app/pdf_generators/hard_copy_generators/form_data_generator.rb
- app/views/qae_form/_steps_progress_bar.html.slim
- spec/support/shared_contexts/download_original_pdf_before_deadline_ends.rb
- spec/support/shared_contexts/pdf_file_checks.rb
https://app.asana.com/0/1200175839265057/1200311085430209
> fix LL pdf link

- app/controllers/application_controller.rb
- app/helpers/form_answer_helper.rb
- app/models/user.rb
- app/views/qae_form/_form_footer.html.slim
- app/views/qae_form/_step_submit.html.slim
- fix LA submission deadline
- fix "Back" link
- remove supporters dependency for user
> Minor local assessment form tweaks

- app/controllers/admin/lieutenants_controller.rb
- app/models/lieutenant.rb
- app/search/form_answer_search.rb
- app/search/lieutenant_search.rb
- app/search/search.rb
- app/views/admin/lieutenants/_form.html.slim
- app/views/admin/lieutenants/_list.html.slim
- app/views/admin/users/_navigation.html.slim
- app/views/admin/users/index.html.slim
- config/locales/en.yml
- db/structure.sql
- spec/acceptance/steps/admin_user_management_steps.rb
- spec/features/admin/lieutenants/manage_spec.rb
note: user type radio is left out for a frontend dev. to change
> Lieutenant management UI changes

- app/controllers/admin/admins_controller.rb
- app/controllers/admin/assessors_controller.rb
- app/controllers/admin/lieutenants_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/admins/confirmations_controller.rb
- app/controllers/assessors/confirmations_controller.rb
- app/controllers/concerns/confirmable.rb
- app/controllers/lieutenant/lieutenants_controller.rb
- app/controllers/lieutenants/confirmations_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/models/admin.rb
- app/models/assessor.rb
- app/models/concerns/password_generatable.rb
- app/models/concerns/password_skippable.rb
- app/models/lieutenant.rb
- app/models/user.rb
- config/routes.rb
https://app.asana.com/0/1200175839265057/1200311149768437
> skip password validation on create and set password after confirmation

- app/assets/javascripts/frontend/ga-optout.js.coffee
- app/views/layouts/_cookie_banner.html.slim
- app/views/layouts/application.html.slim
This PR does the following:
- Fix interactions on cookie banner
- Fix paragraph styling on cookie banner
- Indents logout link under if condition
> Fixing cookie banner

- app/mailers/account_mailers/group_leader_mailer.rb
- app/models/email_notification.rb
- app/renderers/mail_renderer.rb
- app/services/notifiers/email_notification_service.rb
- app/views/account_mailers/group_leader_mailer/notify.text.erb
- app/views/account_mailers/group_leader_mailer/preview/notify.html.slim
- app/views/admin/settings/deadlines/_local_assessment_email_notifications.html.slim
- config/locales/en.yml
- spec/renderers/mail_renderer_spec.rb
- spec/services/notifiers/email_notification_service_spec.rb
https://app.asana.com/0/1200175839265057/1200311222798057/f
> add email notification for group leaders [DEMO]

- app/mailers/account_mailers/group_leader_mailer.rb
- app/models/email_notification.rb
- app/renderers/mail_renderer.rb
- app/services/notifiers/email_notification_service.rb
- app/views/account_mailers/group_leader_mailer/notify.text.erb
- app/views/account_mailers/group_leader_mailer/preview/notify.html.slim
- app/views/admin/settings/_notification.html.slim
- app/views/admin/settings/deadlines/_local_assessment_email_notifications.html.slim
- config/locales/en.yml
- spec/renderers/mail_renderer_spec.rb
- spec/services/notifiers/email_notification_service_spec.rb
https://app.asana.com/0/1200175839265057/1200311222798057/f
settings page is broken with new UX for now
> Group leader notification [new UX]

- app/forms/award_years/v2022/qavs/qavs_step5.rb
- app/views/content_only/_steps_progress_bar.html.slim
- app/views/form_award_eligibilities/_steps_progress_bar.html.slim
- app/views/qae_form/_options_question.html.slim
- app/views/qae_form/_steps_progress_bar.html.slim
https://app.asana.com/0/1200175839265057/1200311085430209
https://drive.google.com/file/d/1HRtgfNZXP4pbUqeLMtsBqRTVv9E6xTPf/view
Changes deadline panel to notification banner
Change to inline radio buttons
Removes header from question 8 and adds notification border to question 9
> govuk style changes and copy tweaks

- app/controllers/content_only_controller.rb
- app/controllers/group_leader/citations_controller.rb
- app/controllers/group_leader/dashboard_controller.rb
- app/helpers/citations_helper.rb
- app/helpers/deadlines_helper.rb
- app/models/citation.rb
- app/models/form_answer.rb
- app/models/group_leader.rb
- app/policies/citation_policy.rb
- app/views/admin/audit_logs/index.html.slim
- app/views/group_leader/citations/_form.html.slim
- app/views/group_leader/citations/edit.html.slim
- app/views/group_leader/dashboard/show.html.slim
- config/initializers/simple_form.rb
- config/routes.rb
- db/migrate/20210808194051_create_citations.rb
- db/migrate/20210809072025_remove_group_leader_from_citations.rb
- db/migrate/20210809072320_add_form_answer_to_citations.rb
- db/migrate/20210809073242_add_form_answer_to_group_leader.rb
- db/structure.sql
- spec/controllers/group_leader/citations_controller_spec.rb
- spec/factories/citations_factory.rb
- spec/features/group_leaders/sign_in_spec.rb
- spec/models/citation_spec.rb
- spec/models/group_leader_spec.rb
https://drive.google.com/drive/folders/1uhYfaoLFho69Uzvi9oE0YII3MxIsy-TQ
https://app.asana.com/0/1200175839265057/1200311196271650
- Adds citation model and controller in the group leader namespace
- Adds citation edit form
- Adds helper method for citation max character count dependent on group name length.
- Timestamps submitted date (to display status tag on dashboard)
- Adds placeholder content for dashboard (needs links to publicity guidance, deadlines updating, and link to palace invite)
> adds citation form

- app/controllers/palace_invites_controller.rb
- app/helpers/text_ordinalize.rb
- app/javascript/packs/application.js
- app/models/palace_attendee.rb
- app/views/palace_invites/_attendee_details.html.slim
- app/views/palace_invites/_form.html.slim
- app/views/palace_invites/edit.html.slim
- config/locales/en.yml
https://docs.google.com/document/d/1fWmoUT212VRkCeqpMjdt5GUPPLeAZ1Wg9BfYYhSkLto/edit
https://drive.google.com/drive/folders/1uhYfaoLFho69Uzvi9oE0YII3MxIsy-TQ
https://app.asana.com/0/1200175839265057/1200311147910821
Updates copy text for questions
- adds Dr option for title
- makes form identical for each attendee
- changes address line labels
- changes options for preferred dates
Adds helper method for text ordinal (can be reused in namespace/form_answer#show)
Fixes accessibility issues on labels
Adds event listener on disabled access radio buttons to disaply important text when yes is pre-selected or clicked.
Removes title validation (not required).
Attendee information is saved but not validated.
> palace invite form update

- app/assets/javascripts/admin/eligibility.js.coffee
- app/assets/stylesheets/admin/page-eligibility.scss
- app/assets/stylesheets/application-admin.scss
- app/controllers/admin/form_answers_controller.rb
- app/decorators/form_answer_decorator.rb
- app/models/form_answer.rb
- app/models/form_answer_state_machine.rb
- app/models/form_answer_state_transition.rb
- app/policies/form_answer_policy.rb
- app/search/form_answer_status/admin_filter.rb
- app/search/form_answer_status/lieutenant_filter.rb
- app/views/admin/form_answers/_applicant_details.html.slim
- app/views/admin/form_answers/_applicant_status.html.slim
- app/views/admin/form_answers/_eligibility_status.html.slim
- app/views/admin/form_answers/eligibility.html.slim
- app/views/admin/form_answers/show.html.slim
- app/views/lieutenant/form_answers/show.html.slim
- config/locales/en.yml
- config/routes.rb
- db/migrate/20210806102135_add_iniligibility_reasons_to_form_answers.rb
- db/structure.sql
- spec/factories/form_answer_factory.rb
- spec/features/admin/form_answers/eligibility_spec.rb
- spec/features/admin/form_answers/withdraw_application_spec.rb
- spec/models/form_answer_state_machine_spec.rb
- spec/models/form_answer_state_transition_spec.rb
- spec/services/assessment_submission_service_spec.rb
https://app.asana.com/0/1200175839265057/1200311188724653
> Admin eligibility

- app/views/admin/form_answers/_bulk_assignment_modal.html.slim
> fixes modal close button

- app/assets/stylesheets/application-admin.scss
Adds right padding to select input
> temp fix to select dropdown

- app/controllers/admin/dashboard_controller.rb
- app/controllers/lieutenant/dashboard_controller.rb
- app/views/layouts/application-admin.html.slim
- spec/features/admin/form_answers/download_all_feedbacks_spec.rb
Redirecting away from dashboard for admins and lieutenants
+ removing 2FA link in menu for admins
> Redirecting away from dashboard for admins and lieutenants

- app/views/admin/form_answers/index.html.slim
- app/views/admin/form_answers/show.html.slim
- app/views/assessor/form_answers/index.html.slim
- app/views/assessor/form_answers/show.html.slim
- app/views/lieutenant/form_answers/index.html.slim
- app/views/lieutenant/form_answers/show.html.slim
- config/routes.rb
- changes search method to post and adds route for admins, lieutenants and assessors
- removes js history from back links
- adds a remove filter button to admins and lieutenants dashboard
> amends nomination filtering

- app/views/admin/form_answers/eligibility.html.slim
- spec/features/admin/form_answers/eligibility_spec.rb
> changes ineligible options to radio buttons

- app/controllers/lieutenant/dashboard_controller.rb
- app/views/layouts/application-lieutenant.html.slim
- app/views/lieutenant/dashboard/show.html.slim
https://app.asana.com/0/1200061634447616/1200794581389264
adds a placeholder landing page for lieutenants.
content tbc
> adds lieutenant dashboard

- app/assets/stylesheets/admin/page-applications.scss
- app/controllers/admin/assessor_assignment_collections_controller.rb
- app/javascript/packs/application.js
- app/models/assessor_assignment_collection.rb
- app/models/assignment_collection.rb
- app/models/form_answer.rb
- app/models/lieutenant_assignment_collection.rb
- app/policies/assessor_assignment_collection_policy.rb
- app/views/admin/form_answers/_bulk_assignment_button_bottom.html.slim
- app/views/admin/form_answers/_bulk_assignment_button_top.html.slim
- app/views/admin/form_answers/_bulk_assignment_modal.html.slim
- app/views/admin/form_answers/list_components/_table.html.slim
- app/views/admin/form_answers/list_components/_table_body.html.slim
- config/locales/en.yml
- config/routes.rb
- db/migrate/20210817084427_add_sub_group_to_form_answers.rb
- db/structure.sql
- spec/features/admin/form_answers/bulk_assessors_assignment_spec.rb
- spec/features/admin/form_answers/bulk_lieutenants_assignment_spec.rb
[part 1. assignment] 
https://app.asana.com/0/1200175839265057/1200311145675920
> bulk assessor assignment

- app/assets/stylesheets/micromodal.scss
- app/javascript/styles/selects.scss
- app/views/admin/form_answers/_bulk_assignment_modal.html.slim
- spec/features/admin/form_answers/bulk_assessors_assignment_spec.rb
- spec/features/admin/form_answers/bulk_lieutenants_assignment_spec.rb
- spec/support/custom_select.rb
> Assessor assignment

- app/views/account_mailers/buckingham_palace_invite_mailer/invite.text.erb
- app/views/account_mailers/buckingham_palace_invite_mailer/preview/invite.html.slim
- app/views/admin/settings/deadlines/_final_stage_email_notifications.html.slim
adds a scheduler for the palace invite for group leaders in the settings page
> adds invite mailer scheduler

- app/views/admin/admins/_form.html.slim
- app/views/admin/assessors/_form.html.slim
- app/views/admin/dashboard/live_data/_applications_in_progress.html.slim
- app/views/admin/group_leaders/_form.html.slim
- app/views/admin/lieutenants/_form.html.slim
- app/views/lieutenant/lieutenants/_form.html.slim
- app/views/shared/users/_password_change.html.slim
- app/views/shared/users/_user_details.html.slim
- adds aria-invalid attribute to password input fields that switches from false to true when the password is invalid
- adds aria-live attribute to the password warning message
- refactors common form partials to apply consistency across the app in styling
> user form password errors accessibility

- app/views/lieutenant/lieutenants/_form.html.slim
fixes indentation on lieutenant/lieutenants#edit
> fixes indentation

- app/views/lieutenant/dashboard/show.html.slim
- spec/features/lieutenant/sign_in_spec.rb
- updates content for LL dashboard
https://docs.google.com/document/d/137smDxCjV4Xj_xr7Z_loNrTCo3YA9duXI8uqaSgoxN8/edit
> LL dashboard

- Gemfile
- Gemfile.lock
- app/models/form_answer.rb
- app/models/form_answer_state_machine.rb
- app/views/admin/form_answers/_applicant_status.html.slim
- spec/rails_helper.rb
- spec/support/pundit_spec_helper.rb
- spec/views/admin/form_answers/applicant_status_spec.rb
Using actual statuses for eligibility and local assessment states on the interim page.
> Nomination statuses fix

- app/controllers/lieutenant/form_answers_controller.rb
- app/controllers/lieutenant/support_letters_controller.rb
- app/policies/form_answer_policy.rb
- app/views/admin/form_answers/_applicant_status.html.slim
- app/views/layouts/application-lieutenant.html.slim
- spec/mailers/account_mailers/notify_non_shortlisted_mailer_spec.rb
> shows success messages on form submissions

- app/views/lieutenant/form_answers/_step_error.html.slim
- app/views/lieutenant/form_answers/edit.html.slim
- app/views/qae_form/_checkbox_seria_question.html.slim
- app/views/qae_form/show.html.slim
- fix check boxes seria question as well
> Fix LA validation on submission

- app/forms/award_years/v2022/qavs/qavs_step5.rb
- app/views/qae_form/_form_footer.html.slim
- adds intro to top of form
- adds 'for example' before examples
> local assessment form copy changes

- app/views/layouts/application-admin.html.slim
- app/views/layouts/application-assessor.html.slim
- app/views/layouts/application-judge.html.slim
- app/views/layouts/application-lieutenant.html.slim
- app/views/layouts/application.html.slim
We will tackle this another way with session extention warnings.
> Remove session notification banner

- app/controllers/concerns/form_answer_submission_mixin.rb
- app/controllers/form_controller.rb
- app/forms/award_years/v2022/qavs.rb
- app/forms/qae_form_builder/qae_form.rb
- app/forms/qae_form_builder/step.rb
- app/views/qae_form/_form_footer.html.slim
- app/views/qae_form/_form_header.html.slim
- app/views/qae_form/_step.html.slim
- app/views/qae_form/_steps_progress_bar.html.slim
- app/views/qae_form/show.html.slim
- config/locales/en.yml
- spec/features/admin/form_answers/create_spec.rb
- spec/features/lieutenant/form_answer_spec.rb
- spec/unit/qae_form_builder_spec.rb
> change step titles and CTAs for admins/lieutenants

- Gemfile
- Gemfile.lock
- app/controllers/concerns/form_answers_pdf.rb
- config/initializers/vigilion.rb
> staging release

- app/assets/stylesheets/frontend/views/eligibility.scss
- app/views/form_award_eligibilities/_answers.html.slim
- app/views/form_award_eligibilities/show.html.slim
* fixes nomination form download link
* styles ineligible question
* styles error message
* left aligns continue button
> adds styling to ineligible question  (#183)

- app/controllers/admin/settings_controller.rb
- app/controllers/application_controller.rb
- app/models/form_answer.rb
- app/views/admin/settings/_bulk_award_success.html.slim
- app/views/admin/settings/show.html.slim
- app/views/admin/settings/stages/_royal_approval_stage.html.slim
- app/views/layouts/_flash.html.slim
- config/routes.rb
https://app.asana.com/0/1200175839265057/1200311194374645
> bulk status update/awarding

- app/assets/stylesheets/frontend/tables.scss
- app/assets/stylesheets/frontend/views/dashboard.scss
- app/views/content_only/_current_nominations.html.slim
- app/views/content_only/_dashboard_past_applications.html.slim
- app/views/content_only/_dashboard_post_submission.html.slim
- app/views/content_only/_dashboard_pre_submission.html.slim
- app/views/content_only/_submitted_applications.html.slim
- app/views/content_only/dashboard.html.slim
- app/views/content_only/past_applications/_combined.html.slim
- app/views/content_only/past_applications/_download_pdf_link.html.slim
- app/views/content_only/post_submission/_submitted.html.slim
- app/views/shared/_application_awards_status.html.slim
- db/seeds.rb
https://drive.google.com/drive/folders/1uhYfaoLFho69Uzvi9oE0YII3MxIsy-TQ
- applies consistent font to rows
- aligns link right
- applies two-third content size
- adds margins around start button
- adds borders to rows
- adds accessibility to table
- removes download link (not in designs)
- uses govuk warning component
> nomination dashboards

- app/assets/javascripts/admin/settings.js.coffee
- app/assets/javascripts/application-admin.js.coffee
- app/assets/javascripts/frontend/form-validation.js.coffee
- app/assets/javascripts/vendor/accessible-autocomplete.min.js
- app/controllers/admin/email_notifications_controller.rb
- app/javascript/vendor/accessible-autocomplete.min.js
- app/views/admin/email_notifications/create.js.erb
- app/views/admin/email_notifications/update.js.erb
- app/views/content_only/info_messages/_award_season_closed.html.slim
- app/views/qae_form/_address_question.html.slim
- db/structure.sql
- spec/controllers/admin/email_notifications_controller_spec.rb
THis PR does the following:
- Changes notification on dashboard after submission deadline is passed
- Fixes address validation for nominators
- Fixes validations for settings deadlines and email scheduling
- Fixes accessible-autocomplete to only trigger change event when the values actually change
> Fixing validations for address questions and dates in settings page

- app/views/qae_form/_supporter_fields.html.slim
- app/views/qae_form/_supporter_fields_placeholder.html.slim
Button only shows now after letter of support is submitted
> Removing remove button before letter of support submission

- app/pdf_generators/qae_pdf_forms/general/question_pointer.rb
empty? cannot be called on an integer
> fix blank pdf download

- app/controllers/admin/email_notifications_controller.rb
- app/views/admin/email_notifications/create.js.erb
- app/views/admin/settings/_notification.html.slim
Issue was not in validation just a rendering issue
> Fixing creation of email notification

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/frontend/accounts.js.coffee
- app/assets/javascripts/frontend/form-validation.js.coffee
- app/assets/javascripts/frontend/password-strength-indicator.js
- app/assets/javascripts/frontend/text-character-count.js
- app/views/layouts/govuk_template.html.erb
- config/initializers/ckeditor.rb
- vendor/assets/javascripts/moment.min.js
These libraries had vulnerabilities in them.
Managed to upgrade fairly easily
> UPgrading CEditor, Moment and jQuery

- app/helpers/application_helper.rb
- app/renderers/qavs_sanitizer.rb
https://app.asana.com/0/1200175839265057/1200969614490752
> custom qavs scrubber for admin comments

- app/models/form_answer_state_machine.rb
- app/search/form_answer_status/admin_filter.rb
- app/views/admin/form_answers/_applicant_status.html.slim
- config/locales/en.yml
https://app.asana.com/0/search/1201016855072035/1200311188724643
> add pending eligibility state

- app/controllers/lieutenant/form_answers_controller.rb
- app/forms/qae_form_builder/step.rb
(vulnerability fix)
https://app.asana.com/0/1200175839265057/1200969614490746
> only allow LL to update local assessment step

- app/controllers/content_only_controller.rb
- app/views/content_only/pre_sign_in.html.slim
- config/routes.rb
> Pre sign in page

- app/policies/form_answer_policy.rb
removes deadline check on edit form answer policy
> temp fix for local assessor form

- app/services/notifiers/email_notification_service.rb
Issue 165 https://docs.google.com/spreadsheets/d/1gHPAcUI7i3dlo2i57Z_II7tUrZ_wVImA683OqEWuJKQ/edit#gid=0
- removes html tags from citation body
> removes tags from citation body

- app/views/content_only/award_info_qavs.html.slim
Issue 156 https://docs.google.com/spreadsheets/d/1gHPAcUI7i3dlo2i57Z_II7tUrZ_wVImA683OqEWuJKQ/edit#gid=0
Updates copy on useful info page to match the sidebar menu items
> updates useful info page to be consistent with side menu

- app/views/account_mailers/group_leader_mailer/notify.text.erb
- app/views/account_mailers/group_leader_mailer/preview/notify.html.slim
- app/views/account_mailers/notify_successful_nominations_mailer/notify.text.erb
- app/views/account_mailers/notify_successful_nominations_mailer/preview/notify.html.slim
- app/views/account_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
- app/views/account_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim
- app/views/account_mailers/reminder_to_submit_mailer/notify.text.erb
- app/views/account_mailers/reminder_to_submit_mailer/preview/notify.html.slim
- app/views/admins/mailer/confirmation_instructions.text.erb
- app/views/admins/mailer/unlock_instructions.text.erb
- app/views/assessors/general_mailer/led_application_withdrawn.text.erb
- app/views/group_leaders_mailers/buckingham_palace_invite_mailer/invite.text.erb
- app/views/group_leaders_mailers/buckingham_palace_invite_mailer/preview/invite.html.slim
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/notify.text.erb
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/preview/notify.html.slim
- app/views/lieutenants/mailer/confirmation_instructions.html.erb
- app/views/lieutenants_mailers/local_assessment_notification_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_notification_mailer/preview/notify.html.slim
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/preview/notify.html.slim
- app/views/users/mailer/confirmation_instructions.html.erb
- app/views/users/mailer/unlock_instructions.html.erb
- app/views/users/submission_mailer/success.text.erb
- app/views/users/submission_started_notification_mailer/notify.text.erb
https://app.asana.com/0/1200061634447616/1201038186257691
- adds a horizontal rule
- adds privacy policy to all emails excluding password reset
> adds privacy policy link to emails

- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/frontend/ga-optout.js.coffee
- app/views/content_only/award_info_qavs.html.slim
- app/views/content_only/cookie_policy.html.slim
- app/views/content_only/cookies.html.slim
- app/views/layouts/_cookie_banner.html.slim
- app/views/layouts/application-judge.html.slim
- app/views/layouts/application-lieutenant.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/twofactor.html.slim
- app/views/users/registrations/new.html.slim
- config/initializers/session_store.rb
- config/routes.rb
This PR:
- adds new cookie policy page
- Changes cookie settings page
- Renames Rails cookie name
- Renames cookies for consents
- Adds links to new pages in footer
Card: https://app.asana.com/0/1176935230183721/1201036488332009/f
> New cookie pages and behaviour

- app/javascript/packs/application.js
- app/javascript/packs/application.scss
- app/views/admin/admins/_list.html.slim
- app/views/admin/assessors/_list.html.slim
- app/views/admin/audit_logs/index.html.slim
- app/views/admin/dashboard/_applications_report.html.slim
- app/views/admin/dashboard/live_data/_applications_in_progress.html.slim
- app/views/admin/dashboard/live_data/_submitted_applications.html.slim
- app/views/admin/dashboard/live_data/_summary.html.slim
- app/views/admin/dashboard/totals_by_day/_registrations.html.slim
- app/views/admin/dashboard/totals_by_month/_registrations.html.slim
- app/views/admin/dashboard/totals_by_week/_registrations.html.slim
- app/views/admin/form_answers/list_components/_table.html.slim
- app/views/admin/group_leaders/_list.html.slim
- app/views/admin/lieutenants/_list.html.slim
- app/views/admin/users/_list.html.slim
- app/views/admin/users/_navigation.html.slim
- app/views/admin/users_feedbacks/show.html.slim
- app/views/content_only/_current_nominations.html.slim
- app/views/content_only/past_applications/_combined.html.slim
- app/views/content_only/post_submission/_submitted.html.slim
- app/views/lieutenant/form_answers/index.html.slim
- app/views/lieutenant/lieutenants/_list.html.slim
Making tables vertical when on mobile
+ adding JS to add ARIAs around so that the tables dont lose semantics
> Making tables responsive and accessible at same time

- app/views/admin/dashboard/live_data/_applications_in_progress.html.slim
- app/views/admin/dashboard/live_data/_submitted_applications.html.slim
- app/views/admin/dashboard/live_data/_summary.html.slim
- app/views/admin/dashboard/totals_by_day/_registrations.html.slim
- app/views/admin/dashboard/totals_by_month/_registrations.html.slim
- app/views/admin/dashboard/totals_by_week/_registrations.html.slim
- app/views/admin/form_answers/list_components/_table.html.slim
- app/views/assessor/form_answers/index.html.slim
- app/views/content_only/_current_nominations.html.slim
Tables mistakenly with font size 14 + 1 table which had bad indentation
> Fixing table font sizes and rendering

- app/forms/award_years/v2022/qavs/qavs_step5.rb
https://app.asana.com/0/1200061634447616/1201114762049127
This PR updates the local assessment form as per the copy below
https://docs.google.com/document/d/1KaBobU9PAuSF6sI36D0DMRFnVWyi-mX4/
> local assessment form updates

- app/assets/javascripts/frontend/form-validation.js.coffee
- app/forms/award_years/v2022/qavs/qavs_step4.rb
- app/forms/qae_form_builder/text_question.rb
- app/helpers/nominee_activity_helper.rb
- app/models/form_answer.rb
- app/search/form_answer_search.rb
- app/services/qavs_data_import.rb
- app/uploaders/file_uploader.rb
- app/uploaders/form_answer_pdf_version_uploader.rb
- db/migrate/20210928120530_add_oid_to_form_answers.rb
- db/structure.sql
- lib/tasks/qavs_v1_data_import.rake
- spec/models/support_letter_attachment_spec.rb
https://app.asana.com/0/1199154381249427/1201017860949485
> Import nominations from QAVSv1 app

- app/controllers/admin/base_controller.rb
- app/controllers/assessor/base_controller.rb
- app/controllers/judge/base_controller.rb
- app/controllers/lieutenant/base_controller.rb
- app/controllers/session_controller.rb
- app/helpers/application_helper.rb
- app/javascript/components/session_timeout.js
- app/javascript/packs/application.js
- app/models/admin.rb
- app/models/assessor.rb
- app/models/group_leader.rb
- app/models/lieutenant.rb
- app/models/user.rb
- app/views/layouts/application-admin.html.slim
- app/views/layouts/application-assessor.html.slim
- app/views/layouts/application-judge.html.slim
- app/views/layouts/application-lieutenant.html.slim
- app/views/shared/_timeout_dialog.html.slim
- config/routes.rb
Implementing dialog to warn users about session timeout, with the ability to extend session.
> Session timeout dialog

- app/javascript/packs/application.scss
- app/views/qae_form/_form_footer.html.slim
This PR does 2 things:
- move back in line with other buttons
- align all buttons
Card: https://app.asana.com/0/1199154381249427/1201346532955969/f
---
> Fixing layout of form footer

- app/models/form_answer.rb
- spec/models/form_answer_spec.rb
https://app.asana.com/0/1199154381249427/1201387817745573/f
> filter out letters of support that have been removed by users

- app/views/admin/form_answers/_details_and_letters_of_support.html.slim
Missing changes from
https://github.com/bitzesty/qavs-v2/pull/333/files
https://app.asana.com/0/1199154381249427/1201387817745573/f
> use active_letters_of_support method on frontend

- app/models/form_answer.rb
- spec/models/form_answer_spec.rb
Continuation of https://github.com/bitzesty/qavs-v2/pull/333
https://app.asana.com/0/1199154381249427/1201387817745573/f
> fix typing issues with letters of support filtering

- app/views/lieutenant/dashboard/index.html.slim
- spec/features/lieutenant/sign_in_spec.rb
removes hyphen from dashboard title
> copy change for LL dashboard

- app/views/layouts/navbar/_assessor.html.slim
https://app.asana.com/0/1200175839265057/1200311220989040
- adds navbar link for new assessor dashboard
> adds dashboard nav link

- app/views/assessor/dashboard/index.html.slim
As per comment here
https://app.asana.com/0/1200175839265057/1200311220989040/f
> upload National Assessor's guidance, hide accessible version link for now

- app/models/reports/national_assessments_report.rb
https://app.asana.com/0/0/1200311197338523/1201559510076348/f
> slim down NA report

- Gemfile.lock
Asana card here: https://app.asana.com/0/0/1201532394693085/f
Tested account creation and password reset and everything working normally after update.
> Bump `devise_zxcvbn` to `6.0.0`

- app/views/content_only/pre_sign_in.html.slim
https://app.asana.com/0/1199154381249427/1201639399867630/f
> add link to NA sign in page

- app/forms/award_years/v2022/qavs/qavs_step1.rb
- app/forms/qae_form_builder.rb
- app/search/form_answer_search.rb
- app/search/form_answer_status/filtering_helper.rb
- app/views/admin/form_answers/index.html.slim
- app/views/admin/form_answers/list_components/_table.html.slim
- app/views/admin/form_answers/list_components/_table_body.html.slim
- app/views/assessor/form_answers/questions/_ceremonial_county_question.html.slim
- app/views/qae_form/_ceremonial_county_question.html.slim
- app/views/shared/form_answers/filters/_nomination_county_filter.html.slim
- spec/features/admin/form_answers/filtering_by_status_spec.rb
- spec/support/form_answer_filtering_test_helper.rb
- remove ceremonial county from nomination form
- change filter for admins to use nominee address county instead of ceremonial county
https://app.asana.com/0/1200175839265057/1201559758877475
> move ceremonial county from nomination form

- app/policies/assessor_assignment_policy.rb
- app/views/admin/form_answers/_section_appraisal_form.html.slim
- spec/support/shared_contexts/appraisal_form_context.rb
https://app.asana.com/0/1199154381249427/1201685731785254
> hide assessment status for assessors until they submit their assessment

- app/controllers/admin/form_answers_controller.rb
- app/decorators/form_answer_decorator.rb
tweaks changes made in https://github.com/bitzesty/qavs-v2/pull/361/files
https://app.asana.com/0/1199154381249427/1201721709653806/f
> remove timestamp from file downlaods

- app/services/notifiers/email_notification_service.rb
- app/views/group_leader/dashboard/index.html.slim
Fix issue with GL dashboard
Refactor GL notifications code to make it failsafe
https://app.asana.com/0/1199154381249427/1201746012169016
> Fix GL dashboard

- app/models/form_answer_state_machine.rb
- spec/models/form_answer_state_machine_spec.rb
https://app.asana.com/0/home/1178339740118267/1201826854672105
> allow eligibility change after form was submitted

- app/forms/award_years/v2023/qavs/qavs_step1.rb
- app/models/eligibility/basic.rb
- app/views/content_only/_award_nickname.html.slim
- app/views/content_only/award_info_qavs.html.slim
- app/views/form_award_eligibilities/basic_questions/_local_area.html.slim
- app/views/form_award_eligibilities/basic_questions/_provide_grants.html.slim
- app/views/form_award_eligibilities/basic_questions/_years_operating.html.slim
- app/views/form_award_eligibilities/show.html.slim
- spec/features/users/eligibility_form_fulfillment_spec.rb
- spec/fixtures/form_answer_qavs.json
- spec/fixtures/form_answer_qavs_with_la.json
- spec/models/eligibility/basic_spec.rb
Card: https://app.asana.com/0/1200061634447616/1201881093051680
Copy changes: https://docs.google.com/document/d/1wf0C6zLmOaY3Zqjbbg-k5kcIeZBlmzaKEnCCbaQ-ylY
Copy updates
Adds new eligibility questions and changes the order
Updates eligible/ineligible message
Copy updates
Adds question A1.2
> [QAVS0222] Updates to eligibility and nomination form

- app/models/eligibility/basic.rb
https://app.asana.com/0/1199154381249427/1201918995852788/
Adds full stops to hints
> [QAVS-0222] QA0703 Adds full stop to hints

- app/models/eligibility/basic.rb
- spec/features/users/eligibility_form_fulfillment_spec.rb
- spec/models/eligibility/basic_spec.rb
https://app.asana.com/0/1199154381249427/1201929204570012
This commit changes the eligible answer for the question "Is its main purpose to raise funds or provide grants for volunteer groups?" from 'Yes' to 'No'.
> Swap acceptance criteria for grants eligibility question

- app/forms/award_years/v2023/qavs/qavs_step3.rb
- app/views/form_award_eligibilities/show.html.slim
https://app.asana.com/0/1199154381249427/1201962537363944
- link added
https://app.asana.com/0/1199154381249427/1201962537363945
- copy change to ineligible alert
> [QAVS0222] - copy changes to nomination form

- app/views/lieutenant/dashboard/index.html.slim
Adds 2022 leaflet guidance to the Lieutenants Dashboard
> Updates leaflets link

- config/initializers/vigilion.rb
https://app.asana.com/0/1201340677821043/1201853404384060/f
> allow connecting to vigilion on a different URL via env

- app/views/group_leader/dashboard/index.html.slim
- spec/features/group_leaders/citation_spec.rb
- spec/features/group_leaders/palace_invite_spec.rb
https://app.asana.com/0/1199154381249427/1202036021642707/f
Some changes need to be made through the settings
> Copy changes and hide submit invite CTAs

- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/notify.text.erb
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/preview/notify.html.slim
https://app.asana.com/0/1199154381249427/1202057858108919/f
> change to special edition

- app/views/group_leader/dashboard/index.html.slim
- spec/features/group_leaders/sign_in_spec.rb
https://app.asana.com/0/1199154381249427/1202036021642707/f
> [QAVS0322] additional copy changes

- Gemfile
- Gemfile.lock
- app/views/shared/_attachment_with_virus_check_status.html.slim
which is before API responds file scanning. enhances copytext message in UI which used to tell user scan was unsuccessful when it is pending
https://app.asana.com/0/home/1178339044569632/1201853404384060
> handle pending status on scans

- app/views/group_leader/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1202036021642707/
- Increase the spacing between ‘What happens next’ and the section header below it.
- Under the 'Lord-Lieutenant presents the Award' section - the sentence: 'The Lord-Lieutenant for your local county, as The Queen's representative, will present' - Can this be changed to too 'As The Queen's representative for your county, The Lord-Lieutenant will present'
- Added link to non-accessible PDF logo guidelines download
- Added link for WP logo guidelines page - replaced with  media pack materials pptx
- Added link for 2022 Media Pack
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202103937470451
- https://app.asana.com/0/0/1202103937470452
- …
> [QAVS0322] Copy changes on GL dashboard

- app/mailers/account_mailers/notify_successful_nominations_mailer.rb
- app/mailers/account_mailers/notify_unsuccessful_nominations_mailer.rb
- app/mailers/group_leaders_mailers/buckingham_palace_invite_mailer.rb
- app/mailers/group_leaders_mailers/winners_head_of_organisation_mailer.rb
https://app.asana.com/0/1199154381249427/1202154120762861/f
> fix final stage email deadlines

- app/renderers/mail_renderer.rb
- app/views/admin/settings/_email_notification.html.slim
- spec/renderers/mail_renderer_spec.rb
https://app.asana.com/0/1199154381249427/1202154120762861/f
> use proper award year for the email previews

- app/views/group_leader/citations/_form.html.slim
- app/views/group_leader/citations/edit.html.slim
- app/views/group_leader/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1202166612587024
> change gl dashboard and citation form copy

- app/models/group_leader.rb
https://app.asana.com/0/1199154381249427/1202168323429219/f
discussion:
https://bitzesty.slack.com/archives/C02E7L0L7/p1650883959945819?thread_ts=1650882816.363299&cid=C02E7L0L7
> fix GL invitation link expiring too fast

- app/assets/stylesheets/frontend/layout.scss
- app/controllers/group_leader/citations_controller.rb
- app/javascript/packs/application.js
- app/policies/citation_policy.rb
- app/views/group_leader/citations/_form.html.slim
- app/views/group_leader/citations/reject.html.slim
- app/views/group_leader/dashboard/index.html.slim
- config/routes.rb
- spec/features/group_leaders/citation_spec.rb
https://app.asana.com/0/home/1178339740118267/1202166612587024
> add ability to reject QAVS award

- app/controllers/admin/citations_controller.rb
- app/models/reports/citation_report.rb
- app/models/reports/form_answer.rb
- app/views/admin/form_answers/_csv_reports_links.html.slim
- change filename
- change link name
- add new column with original citation
- update citation column name
https://app.asana.com/0/1199154381249427/1202218865406989/f
> tweak citation csv report

- package-lock.json
- package.json
Card: https://app.asana.com/0/1199154381249427/1202224535654562/f
Addressing vulnerabilities in [dependabot report ](https://github.com/bitzesty/qavs-v2/security/dependabot)
- Upgrades node-forge to 1.3.0
- Upgrades ansi-html to 0.0.8
- Upgrades glob-parent to 5.1.2
> Npm package upgrades

- app/views/lieutenant/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1202244819375873/f
Adds latest media pack download
> Adds 2022 media pack link for LL dashboard

- app/views/lieutenant/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1202266848469077
Updates the link to a guidance page with more available files to download
> Updates link for logo guidance on lieutenant dashboard

- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim
- spec/mailers/group_leader_mailers/notify_unsuccessful_nominations_mailer_spec.rb
- spec/renderers/mail_renderer_spec.rb
https://app.asana.com/0/1199154381249427/1202305344458486/f
> change unsuccessful gl email copy

- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim
https://app.asana.com/0/1199154381249427/1202305344458486
> remove the dot from the gl email copy

- app/views/account_mailers/notify_successful_nominations_mailer/notify.text.erb
- app/views/account_mailers/notify_successful_nominations_mailer/preview/notify.html.slim
https://app.asana.com/0/1200061634447616/1202339703930597
> [QAVS0522] Changes to the 'SUCCESSFUL: Email to nominators

- app/mailers/lieutenants_mailers/local_assessment_notification_mailer.rb
https://app.asana.com/0/1199154381249427/1202962075142240/
Scopes the total application count for lieutenants on the mailer to only include eligible applications in the current year
> Scope LL applications total in mailer

- app/forms/award_years/v2023/qavs/qavs_step5.rb
- app/forms/qae_form_builder/question.rb
- app/views/qae_form/_question.html.slim
https://app.asana.com/0/1199154381249427/1202962075142234
- this year the PDF forms have diverged from the online form. The PDF questions display less help text  and so to accommodate this, a new method has been added `def online_context(text)` which will only display text on the online form, and not the PDF form.
> Local assessment update 2022

- app/views/lieutenant/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1203050572888016
New guidance uploaded to google cloud and link on Lieutenant dashboard updated
> Updates LL guidance link for 2023

- app/forms/award_years/v2023/qavs/qavs_step5.rb
https://app.asana.com/0/1200061634447616/1203047747098548/
QA - changes
> QA-changes

- app/forms/award_years/v2023/qavs/qavs_step5.rb
https://app.asana.com/0/1199154381249427/1203047747098559
Copy changes following QA 29/09
> QA changes 29-09 to local assessment

- app/forms/award_years/v2023/qavs/qavs_step5.rb
- app/pdf_generators/qae_pdf_forms/general/draw_elements.rb
- app/views/lieutenant/dashboard/index.html.slim
https://app.asana.com/0/1199154381249427/1203073014258915
https://app.asana.com/0/1199154381249427/1203073014258919
> Local Assessment form changes QA 30-09

- app/models/reports/assessment.rb
https://app.asana.com/0/1199154381249427/1203705443520139/f
> Remove no when assessment unsubmitted

- app/forms/award_years/v2024/qavs/qavs_step2.rb
Card:  https://app.asana.com/0/1199154381249427/1203903737993811/f
> Copy change 'your' to 'the' in nomination form

- Gemfile
- Gemfile.lock
- config.ru
* Adds canonical host to handle redirects
* https://app.asana.com/0/1199154381249427/1203669124058962/f
* Need to add environment variable
> [STAGING] Add rack-canonical-host gem

- app/value_objects/server_environment.rb
* Changes the value of expected mailer_host for each environment to match environment variables
* https://app.asana.com/0/1199154381249427/1203669124058962
* None
> Updates mailer_host variable checks

- app/views/qae_form/confirm.html.slim
* Updates timeline
* https://app.asana.com/0/1199154381249427/1204749901484404/f
*
> Timeline copy changes

- Gemfile.lock
* Upgrades sanitize to 6.0.2 
* https://app.asana.com/0/1199154381249427/1205069970096658/f
*
> Upgrades sanitize 

- app/helpers/form_answer_helper.rb
- spec/features/admin/form_answers/list_sorting_spec.rb
- spec/features/assessor/list_sorting_spec.rb
- spec/support/shared_contexts/form_answers_table_sorting.rb
* Removes condition to display bulk assignment depending on submission deadline
* https://app.asana.com/0/1199154381249427/1205077972633899/f
*
> Allow assignment of lieutenancy regardless of submission deadline

- app/views/content_only/past_applications/_combined.html.slim
* Avoids 'Successful' and 'Pending verdict' both appearing
* https://app.asana.com/0/1199154381249427/1205331920077670
*
> Correcting conditional statement

- app/views/accounts/useful_information.html.slim
- app/views/content_only/_guidance_notes.html.slim
- app/views/content_only/_steps_progress_bar.html.slim
- app/views/feedbacks/show.html.slim
- app/views/form_award_eligibilities/_steps_progress_bar.html.slim
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/notify.text.erb
- app/views/group_leaders_mailers/notify_unsuccessful_nominations_mailer/preview/notify.html.slim
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/notify.text.erb
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/preview/notify.html.slim
- app/views/layouts/application-admin.html.slim
- app/views/layouts/application-assessor.html.slim
- app/views/layouts/application-judge.html.slim
- app/views/layouts/application-lieutenant.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/twofactor.html.slim
- app/views/lieutenants_mailers/local_assessment_notification_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_notification_mailer/preview/notify.html.slim
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/notify.text.erb
- app/views/lieutenants_mailers/local_assessment_reminder_mailer/preview/notify.html.slim
- app/views/palace_invites/_attendee_details.html.slim
- app/views/palace_invites/edit.html.slim
- app/views/qae_form/_steps_progress_bar.html.slim
- app/views/users/submission_mailer/success.text.erb
- public/404.html
- public/422.html
* Removes all references to phone number
* https://app.asana.com/0/1199154381249427/1205464003424789/f
*
> Remove all references to phone number

- app/views/group_leader/dashboard/index.html.slim
* Copy changes to update for the new award year
* https://app.asana.com/0/1199154381249427/1205520461778251/f
* None
> Copy changes to group leader dashboard

- app/assets/stylesheets/frontend/layout.scss
- app/views/group_leader/dashboard/index.html.slim
* Increase the width of the deadline column to fit all on one line
* https://app.asana.com/0/1199154381249427/1205520461778251
* None
> Increase width of deadline column on GL dashboard

- app/views/group_leader/citations/_form.html.slim
* Updates citation help copy
* https://app.asana.com/0/1199154381249427/1205520461778251
* None
> Updates citation help copy

- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/notify.text.erb
- app/views/group_leaders_mailers/winners_head_of_organisation_mailer/preview/notify.html.slim
* Copy update on the group leader winners mailer to add the dashboard link
* https://app.asana.com/0/1199154381249427/1205584186803944/f
* None
> Adds root url to GL mailer

- app/views/group_leader/dashboard/index.html.slim
* Updates link copy and url to update for the new award year
* https://app.asana.com/0/1199154381249427/1205640829559037/f
* Files do not exist yet so should not deploy to production until files have been uploaded
> Updates group leader dashboard winners pack links

- app/views/group_leader/dashboard/index.html.slim
* Updates links to refer to KAVS instead of QAVS in the url 
* https://app.asana.com/0/1199154381249427/1205640829559037/f
* None
> Updates links in group leader dashboard for KAVS

- app/views/group_leader/dashboard/index.html.slim
* copy
* https://app.asana.com/0/1199154381249427/1205709443612976/f
*
> update copy (fix incorrect year)

- app/views/group_leader/dashboard/index.html.slim
* copy
* https://app.asana.com/0/1199154381249427/1205709443612976/f
*
> change gl dashboard copy

- app/models/reports/local_assessment_report.rb
- app/models/reports/nomination.rb
* Add new nominee website column to local assessment csv report
* https://app.asana.com/0/1199154381249427/1205845509988755/f
*
> Add new nominee website column to local assessment csv report

- app/views/lieutenant/dashboard/index.html.slim
* Update links in lieutenants dashboard to updated resources on google storage
* https://app.asana.com/0/1199154381249427/1205845509988763/f
*
> Update lieutenants dashboard

- app/views/lieutenant/dashboard/index.html.slim
* 
* https://app.asana.com/0/1199154381249427/1205845509988763/f
*
> Swap order of copy in lieutenant dashboard links

- app/controllers/assessor/form_answers_controller.rb
- config/locales/en.yml
* add missing translation
* add verdict to national assessors
https://app.asana.com/0/1199154381249427/1205364676770334
> tweaks after rails upgrade

- Gemfile.lock
- app/views/account_mailers/group_leader_mailer/notify.text.erb
- app/views/account_mailers/group_leader_mailer/preview/notify.html.slim
- spec/mailers/account_mailers/group_leader_mailer_spec.rb
* Copy change
* https://app.asana.com/0/1199154381249427/1206056810287705/f 
* https://docs.google.com/document/d/1D39ff49hJwS2-K1SPnw78EhR66U2GNmYbhpfmXrbNj4/edit
* None
> Copy changer on GL nomination mailer

- .github/workflows/ci.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- config/environments/production.rb
- package-lock.json
- package.json
- yarn.lock
update docker image for ruby 3.2.2 and rails 7
> fix docker image building

- Dockerfile
circleci image gives `error building image: error building stage: failed to get filesystem from image: mkdir /usr/include/mysql: file exists`
> use pure ruby image to build with gcloud

- app/policies/support_letter_policy.rb
- app/views/qae_form/_supporter_fields.html.slim
* https://github.com/bitzesty/qavs-v2/pull/631
* https://github.com/bitzesty/qavs-v2/pull/633
* https://github.com/bitzesty/qavs-v2/pull/634
> [STAGING] - allow admins to remove letters of support

- app/views/group_leader/dashboard/index.html.slim
* copy change
* https://docs.google.com/spreadsheets/d/1csjiPXM8i-FQ6wzOqEMFTmDOVXA_znAj7CXHzht7Mwk/edit#gid=0
> remove year duplication on GL dashboard

- app/views/admin/lieutenants/_list.html.slim
* remove link to deleted lieutenants
* https://app.asana.com/0/1199154381249427/1206111043854989/f
*
> remove link to deleted lieutenants

- forms/award_years/v2022/qavs/qavs_step4.rb
- forms/award_years/v2023/qavs/qavs_step4.rb
- forms/award_years/v2024/qavs/qavs_step4.rb
- forms/award_years/v2025/qavs/qavs_step4.rb
* open privacy notice in new tab
* https://app.asana.com/0/1199154381249427/1206476387974022/f
*
> open privacy notice in new tab

- app/assets/javascripts/frontend/form-validation.js.coffee
- app/views/qae_form/show.html.slim
* change validation copy
* https://app.asana.com/0/1199154381249427/1206476387974014/f
*
> validation copy update

- app/views/assessor/dashboard/index.html.slim
* Adds guidance links to the assessor dashboard to make more similar to the LL dashboard
* https://app.asana.com/0/1199154381249427/1206580439748053/f
* None
> Adds new links to assessors dashboard

- app/views/assessor/dashboard/index.html.slim
* Copy change
* https://app.asana.com/0/1199154381249427/1206580439748047
* None
> Assessor dashboard copy change

- app/views/assessor/dashboard/index.html.slim
* Copy changes and removes unused links
* https://app.asana.com/0/1199154381249427/1206580439748053/f
* None
> Copy changes to assessor dashboard

- app/views/assessor/dashboard/index.html.slim
* Adds new assessor guidance link
* https://app.asana.com/0/1199154381249427/1206580439748053/f
* None
> Adds new assessor guidance link

- app/views/admin/lieutenants/index.html.slim
- app/views/shared/form_answers/filters/_assigned_lieutenancy_filter.html.slim
* 
asana: https://app.asana.com/0/1199154381249427/1206750664011262/f
*
> Set Select all by default

- app/views/content_only/info_messages/_award_season_closed.html.slim
* Changed ‘May’ to ‘September’ in pre-award opening dashboard message
* https://app.asana.com/0/1199154381249427/1207550978457721/f
*
> Update dashboard copy

- forms/award_years/v2025/qavs/qavs_step3.rb
Signed-off-by: Louis Kirkham <louis.kirkham@bitzesty.com>
* Adds PDF context for letters of support question
* https://app.asana.com/0/1199154381249427/1207863714230613/f
* None
> Formatting for support letters pdf section

- Gemfile.lock
- app/helpers/application_helper.rb
- app/models/eligibility/basic.rb
- app/views/accounts/useful_information.html.slim
- app/views/content_only/_award_nickname.html.slim
- app/views/content_only/award_info_qavs.html.slim
- app/views/form_award_eligibilities/basic_questions/_involved_with_group.html.slim
- app/views/form_award_eligibilities/show.html.slim
- app/views/layouts/application.html.slim
- app/views/qae_form/confirm.html.slim
- forms/award_years/v2025/qavs/qavs_step1.rb
- forms/award_years/v2025/qavs/qavs_step2.rb
- forms/award_years/v2025/qavs/qavs_step4.rb
- spec/factories/eligibility.rb
- spec/features/admin/form_answers/filtering_by_status_spec.rb
- spec/features/assessor/filtering_spec.rb
- spec/features/lieutenant/filtering_spec.rb
- spec/features/users/eligibility_form_fulfillment_spec.rb
- spec/fixtures/form_answer_qavs.json
- spec/fixtures/form_answer_qavs_with_la.json
- spec/models/eligibility/basic_spec.rb
- spec/models/form_answer_spec.rb
The Process page
* Copy changes
Eligibility
* Adds new question
* Copy changes to other questions
Award Form
* A section copy changes
* Makes secondary activity required
* B section copy changes
* D section copy changes
Useful information
* Copy changes
* Excludes footer
What happens next
* Updates dates
* https://app.asana.com/0/1199154381249427/1207978380074941/f
* None
> Form and eligibility changes

- app/assets/stylesheets/frontend/forms.scss
- forms/award_years/v2025/qavs/qavs_step1.rb
- forms/award_years/v2025/qavs/qavs_step2.rb
* Copy changes for A and B sections of award form following QA
* https://app.asana.com/0/1199154381249427/1207987401383681/f
* None
> Copy changes to award form

- app/pdf_generators/qae_pdf_forms/general/question_pointer.rb
- forms/award_years/v2025/qavs/qavs_step2.rb
* Adds space between list and paragraph on B1.1
* Adds form_hint to PDF renderer
* https://app.asana.com/0/1199154381249427/1207987401383681/f
* None
> Applies PDF formatting changes to award form

- app/models/reports/nomination.rb
- app/models/reports/nominations_report.rb
- spec/models/reports/nominations_report_spec.rb
* Adds new columns for award form questions A1.2, B1, B2, B3, B4
* Refactors inherited `sanitize_string` method to allow new lines. Calls strip to remove leading and trailing whitespace
* https://app.asana.com/0/1199154381249427/1207920262786648/f
* None
> Adds additional columns to NominationsReport

- forms/award_years/v2025/qavs/qavs_step2.rb
* Remove unnecessary punctuation in KAE form
* https://app.asana.com/0/1199154381249427/1208032411591111/f
* None
> chore: Remove unnecessary punctuation in KAE form

- app/assets/stylesheets/admin/tables.scss
- app/controllers/admin/protected_files_controller.rb
- app/controllers/admin/statistics/nominations_controller.rb
- app/controllers/concerns/protected_file_mixin.rb
- app/mailers/admin/statistics/nomination_mailer.rb
- app/models/admin.rb
- app/models/assessor.rb
- app/models/group_leader.rb
- app/models/lieutenant.rb
- app/models/protected_file.rb
- app/models/user.rb
- app/policies/statistics_policy.rb
- app/search/nomination_stats_search.rb
- app/uploaders/protected_file_uploader.rb
- app/views/admin/statistics/nomination_mailer/notify.html.slim
- app/views/admin/statistics/nominations/_list.html.slim
- app/views/admin/statistics/nominations/index.html.slim
- app/views/layouts/navbar/_admin.html.slim
- config/routes.rb
- db/migrate/20240819123818_enable_extension_pgcrypto.rb
- db/migrate/20240819143818_create_protected_files.rb
- db/structure.sql
Added nomination statistics with one table so far. Stats can be exported and the file is then persisted and link sent to user. 
Asana card here: https://app.asana.com/0/1199154381249427/1206750664011256/f 
Added `pgcrypto` PostgreSQL extension.
> [KAVS0824] Nomination statistics report

- app/assets/javascripts/frontend/custom_questions/support_letters.js.coffee
- app/assets/javascripts/frontend/form-validation.js.coffee
- app/controllers/form/support_letters_controller.rb
- app/views/form/support_letters/_form.html.slim
- app/views/qae_form/_supporter_fields.html.slim
* Fix missing value validation on Letters of Support subquestions
* https://app.asana.com/0/1199154381249427/1208016917079089/f
*
> Fix missing value validation on Letters of Support subquestions

- app/search/nomination_stats_search.rb
- app/views/admin/statistics/nominations/_list.html.slim
Re-worked statistics table to display rows w/ 0 values if they are included in filter.
Asana card here: https://app.asana.com/0/1199154381249427/1208293151383136/f
None
> [KAVS0924] Re-work statistics table to display rows w/ 0 values

- app/views/group_leader/dashboard/index.html.slim
* Copy changes to update the group leader dashboard for the new award year
* None
> chore: Update date and year in dashboard index.html.slim

- app/views/group_leader/dashboard/index.html.slim
* Fixes incorrect years used in dashboard
* None
> chore: Update year in dashboard index.html.slim

- app/views/group_leader/citations/edit.html.slim
* @award_year is assigned to the current year so this change uses the award year of the form answer associated to the application
* None
> chore: Update variable for citation award year in group leader citations edit page

- Gemfile
- Gemfile.lock
* Minor version security updates
* https://app.asana.com/1/18526863193321/project/1199154381249427/task/1209993244479152
* None
> chore: bundler updates

- app/views/group_leader/dashboard/index.html.slim
* Capitalises timeline entry
* Years and media pack links will be updated automatically
* https://app.asana.com/0/0/1211507947175501/f
* https://docs.google.com/document/d/1m7zBxH6W6q0JZqjR3mR0OHsSonqZI_PTAGH2MRbCRts/edit?tab=t.0
* None
> copy: update group leader dashboard

- app/views/group_leader/dashboard/index.html.slim
* Copy change to group leader timeline. Remove settings date and use hardcoded flexible date
* https://app.asana.com/0/0/1211507947175501/f
* None
> copy: timeline copy change

- .actrc
- .github/workflows/ci.yml
https://github.com/bitzesty/qavs-v2/pull/741
> [STAGING] chore: update workflow to latest stable versions

- app/views/group_leader/dashboard/index.html.slim
https://github.com/bitzesty/qavs-v2/pull/744
https://github.com/bitzesty/qavs-v2/pull/745
> [STAGING] copy: updates group leader dashboard timeline

- app/views/group_leader/dashboard/index.html.slim
https://github.com/bitzesty/qavs-v2/pull/744
https://github.com/bitzesty/qavs-v2/pull/745
> [PRODUCTION] copy: updates group leader dashboard timeline
